### ISSUE TITLE
Youtube not scrolling down on microsoft-edge

### ISSUE THREAD

**Issue by ProgmRuanSilva** [gdh1995/vimium-c#1014]
**Describe the bug**
When i try scrolling down on youtube site it does not respond

Hello I'm currently using the plugin was 2 weeks ago 
and it has worked correctly until now, this bug just appears 
on youtube page, when I tried scrolling down just not work.
i repeat this error only appears on youtube page. I don't know 
if this erros is for youtube or the plugin, or another person like
me face the same problem. for now thank you 🙃 

**To Reproduce**

just open the youtube page and try scrolling down

1. Go to URL "www.youtube.com"
2. try scrolling page with shortcuts

**Browser, OS and Vimium C versions**

- Browser name: microsof-edge-dev
- Browser version: 118.0.2088.33
- Vimium C version: 1.99.99
- OS name and version: Kubuntu 22.04.03 LTS x86_64

**Comment by gdh1995** [comment]
I'm not sure what's the root cause of this issue report. Maybe it's because:
- Vimium C scrolled some other page elements, like the left sidebar
  - if you click (or LinkHints-activated) some page element, then scrolling commands will prefer the element and its outer boxes

So, when you meet this issue, you may click the page center and try scrolling keys again.

You may also:
- use `LinkHints.activate` and activate "dark red" hint markers - the color means the marked elements are scrollable
- use `LinkHints.activateHover` and activate any hint marker "pointing to any child element inside your target scrollable area"
