### ISSUE TITLE
Broken sometimes after going back

### ISSUE THREAD

**Issue by Frederick888** [gdh1995/vimium-c#1016]
**Describe the bug**

Vimium-C is sometimes broken after going back.

**To Reproduce**

1. Open a new tab
2. Paste https://aur.archlinux.org/packages/2048-cli-git into the address bar and hit Enter
3. `f` and choose the Upstream URL https://github.com/tiehuis/2048-cli
4. `H` to go back to AUR from GitHub
5. `f` again and nothing happens

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 119.0b7
- Vimium C version: 1.99.995
- OS name and version: `Linux 6.5.6-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Oct 2023 08:14:55 +0000`

**Comment by gdh1995** [comment]
Confirmed. Too strange..

**Comment by gdh1995** [comment]
Currently, you may use system or Firefox shortcuts to switch to another program window / tab, and then switch back - Vimium C will re-activate something and then work again.

**Comment by gdh1995** [comment]
Hello, after quite a few tests, I noticed that:
1. when Vimium C shortcuts fail, Firefox's built-in shorcuts like `Tab` to switch focus also fail
2. if during a try it fails, you may re-enable shortcut keys by just moving mouse over page content 

So now I believe it's a bug of Firefox Beta and the root cause is:
1. after `goBack` Firefox makes something wrong and a current tab loses its "focused" state,
2. so no keyboard events will be sent to the tab

**Comment by Frederick888** [comment]
@gdh1995 Thank you for the investigation! It seems this issue is gone in 119.0b9.
