### ISSUE TITLE
Android mobile

### ISSUE THREAD

**Issue by Freed-Wu** [gdh1995/vimium-c#1095]
**What command or commands**

Firefox mobile support addons:

https://addons.mozilla.org/en-US/android/

Is it possible to release a version for android pad?

Related issues in vimium: https://github.com/philc/vimium/issues/2208

**Comment by Freed-Wu** [comment]
> Already works (not fully) on android mobile.

Hey, can it be published to https://addons.mozilla.org/en-US/android/

**Comment by gdh1995** [comment]
Vimium C is not marked as Firefox+Android compatiable, mainly because code of its tabs and windows commands need lots of reviews before working.

And I have no such Android Pad device (except Windows Subsystem for Android), so I haven't spent enough time to test it. Sorry.

In the future months of 2024 I have no time to begin this heavy work.

**Comment by shamefulCake1** [comment]
Duplicate https://github.com/gdh1995/vimium-c/issues/1055

But yes, this would have been very nice. 

Stock Fennec is bad at working with hotkeys. No ctrl+tab, no ctrl+w.

**Comment by Freed-Wu** [comment]
Repeated by #1055.
