### ISSUE TITLE
How can website detect if vimium-c is running?

### ISSUE THREAD

**Issue by gqqnbig** [gdh1995/vimium-c#130]
Some vimium-c keybindings conflicts when the shortcuts on my website. 

I would like my website to detect if users are using vimium-c and give a message.

How can website detect if vimium-c is running?

**Comment by gdh1995** [comment]
Um, currently no a unified method to do this, because Vimium and Vimium C are trying to avoid "influence" normal web pages (there've been some discussions in Vimium's Issues panel).

Anyway, there indeed exist some methods to detect it. For example:
* on Firefox, check `window.__VimiumC_priv__ != null`
* on Chrome, use a XHR to request `chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/lib/injector.js`
* on Chrome and **before** Vimium C v1.81 (not released yet), you can:
  * check `["()=>1", "() => 1"].includes("" + ((__VimiumC_)=>1))`
  * the reason is Vimium C replaces all function body whose `.indexOf('__VimiumC_') > 0` with `"" + (() => 1)`, so you can do such a test
  * but this strange logic is just a typo and will be removed in Vimium C v1.81, in up to a month.
