### ISSUE TITLE
Translating to FR, i require additional information

### ISSUE THREAD

**Issue by Bumbadawg** [gdh1995/vimium-c#142]
Hi,

I'm translating to FR / french locales for a future pull request, 
but i need a bit of explanations as i don't know how to test all the strings to put them in context.

1. only english locales have "*_p" entries, being the function usage. Shall i translate those as well or keep them out ?
2. the function "Toggle switch only on current page":  which switch are you refering to ?
3. you sometimes use "for once": do you imply "once" as in doing something one time ?
4. _o141_ "keeps to", can you put this sentence in context ?
5. "open this URL in incognito mode": (it's a question for many messages beginning with verbs actually)
  * do you mean the declarative form "it opens" 
  * or the imperative form "please open", 
  * or the infinitive form "to open" ? 

6. Do you have a test for checking messages locales ?
7. Do i need to modify another file so that this FR locale gets detected ?

Cheers.

**Comment by gdh1995** [comment]
Oh thank you.

#### `_p`

Those ending with `_p` in `en/messages.json` means available "parameters" of commands, and those main parts before `_p` is names of target commands. For example, `openUrl_p ... "url:string, urls:string[], reuse=-1/0/1/-2, incognito, window, position"` means the command of `openUrl` supports `<string>` `url`, or `<string[]>` `urls`, and its `reuse` option can be -1, 0, 1 or -2 ...

Those ending with `_s` 

#### toggleSwitchTemp

`toggleSwitchTemp` is a command to only change some settings (which are originally configured on options page) on a current tab, and its effect will disappear when a page reloads / another page is opened in the tab.

For example, `map *** toggleSwitchTemp key="ignoreKeyboardLayout"` means to toggle the "Ignore keyboard layout" option; `map *** toggleSwitchTemp key="scrollStepSize" value=200` means to use a larger step when scrolling.

In the first time a `toggleSwitchTemp` executes, it changes the specified setting item, while a second time will revert back the setting.

#### "for once"

Um, yes. My English is not so good, and if "for once" is not a legal usage, please help me fix it.

#### o141

Those of "`o` + Number" are mainly for the Vimium C Options page and the popup panel when one clicks the extension icon, and you can search them directly. So you can see `o141` in line 662 of `pages/options_base.ts`, and `stateAction` is `$<EnsuredMountedHTMLElement>("#state-action")` in line 572, while `#state-action` refers to the top line of popup panel (line 87 of `pages/popup.html`).

Those pure number items are for content scripts, and there's a definition named `kTip` in the head of `types/messages.d.ts`. Many commands use the id to format messages and show text in the HUD. Some other numbers which are not in `kTip` are for `LinkHints` only and represent different modes.

#### messages beginning with verbs

Messages only represent a current status or what's the next to do, and they're always showing on explicit user actions, so I personally think, it's OKay to use not a full sentence but some shorter words.

And [philc/vimium](https://github.com/philc/vimium) has used these verbs for many years.

#### test for checking locales

Um, no test code for it.

Whenever you modify a `messages.json`, you'll have to reload the whole extension on `chrome://extensions/?id=hfjbmagddngcpeloejdejnfgbamkjaeg` (Chrome) or `about:debugging#/runtime/this-firefox` (Firefox), so that the extension can read those changes.

I usually uses `chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html` to test both text in options page and tips used by content scripts.

On Firefox, there's another key point you should notice: Vimium C caches all available message keys. So if you add some keys (e.g. split one message to two parts), you need to run `localStorage.removeItem("i18n_f")` on the console of Vimium C Options page, and then reload the extension.

#### modify another file so that this FR locale gets detected

The new file should be `_locales/fr/messages.json`,  and then you can run `chrome --lang=fr` from a console / terminal window. On Firefox, you need to open `about:preferences`, choose another language like French and add it, then Firefox will download the language package and restart to apply it.

**Comment by Bumbadawg** [comment]
Many thanks for the detailed explanations. 
Your addon is now frenched ; although for the "oXXX" verbs there might be some losses in translation, i'll adapt through further testing.
As for english, i corrected a bit of your translation.
I haven't tested it yet.
https://github.com/gdh1995/vimium-c/pull/145
