### ISSUE TITLE
Do not auto enter insert mode

### ISSUE THREAD

**Issue by ThePonyCoder** [gdh1995/vimium-c#164]
Is there an option, not to enter insert mode automatically, cause some pages with JavaScript can do this. For example vk.com is hard to use vimium-c. What is more there is no hud info, like when you enter insert mode manually

**Comment by gdh1995** [comment]
If you mean not to focus an input box when a page is loading, then there's an advanced option of "Don't let pages steal the focus in loading" on Vimium C's options page.

If you want to keep Vimium C's shortcuts usable whenever an input box is focused, here's some advices:
* press <kbd>Esc</kbd> or <kbd>Ctrl+[</kbd> to "blur" input boxes and then Vimium C will go back to normal mode and consume following keys
  * `<esc>` and `<c-[>` can be mapped. For example, `mapkey <c-]> <esc>` will make <kbd>Ctrl+]</kbd> (during Vimium C consumes it) work like <kbd>Esc</kbd>
  * there's a command named `switchFocus`, and you may use it to re-focus the most-recently-focused input box, when you have pressed <kbd>Esc</kbd>
* map some keys which contains <kbd>F1</kbd> ~ <kbd>F12</kbd>
  * Vimium C will keep such keys, whose main key is F1~F12, usable even in a default insert mode
    * of course not in the insert mode entered by the command `enterInsertMode`
  * For example, `map <s-f8> LinkHints.activate` makes <kbd>Shift+F8</kbd> always trigger LinkHints mode
  * But `map <f8>f LinkHints.activate` can not be triggered in a default insert mode, because the second key, `f`, is not in F1~F12
    * if press `<f8>` and then `f`, then `<f8>` will be consumed by Vimium C, and `f` will be passed through to a input box itself.
* configure global shortcuts on `chrome://extensions/shortcuts`
  * command shortcuts configured here are always usable
  * if the command you want is not in the list, you may setup "User Customized" 1 and 2, and add something like `shortcut userCustomized1 command="goBack"` into "Custom key mappings" on Vimium C Options page
  * if the 2 placeholders are not enough, there's an assistant extension named [Shortcut Forwarding Tool](https://chrome.google.com/webstore/detail/shortcut-forwarding-tool/clnalilglegcjmlgenoppklmfppddien) to let you setup more.

**Comment by ThePonyCoder** [comment]
> If you mean not to focus an input box when a page is loading, then there's an advanced option of "Don't let pages steal the focus in loading" on Vimium C's options page.

That is what I need, but it looks like it doesn't work

Here is video with demostration.
[https://youtu.be/3W1Wn1rAvI0](url)

**Comment by gdh1995** [comment]
Um, this issue indeed exists, because Vimium C didn't think the whole page was loading after you clicked a button - the page's code just downloaded some info and replaced an area of things.

If you test it on Vimium, then Vimium will prevent such focusing, since it also runs a similar logic when the LinkHints-activated item is a button or link.

But personally I think Vimium's logic can not be very accurate, so I have removed it in Vimium C.

**Comment by ThePonyCoder** [comment]
>then Vimium will prevent such focusing

No, with Vimium the problem also exists. What is more, qutebrowser don't enter insert mode, but the forms steal focus, and controls don't work
So, as I understand, there is no solution, just typing escape everytime?

**Comment by gdh1995** [comment]
Um, seems no solution.

**Comment by casprwang** [comment]
[cVim](https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh?hl=en) has a `set noautofocus` option for this exact behavior. It works for most of the site I know, including vk.com

Here's the implementation: https://github.com/1995eaton/chromium-vim/commit/1541b17c60001f15fa0e9f90075ae2b247e91d55 

Looks pretty naive, but it does the job. Maybe it's worth adopting for `vimium-c`.

**Comment by gdh1995** [comment]
&nbsp;Well, I think there has been such an option: in the advanced options section, a checkbox named "Don't let pages steal the focus in loading".



---Original---

**Comment by casprwang** [comment]
Ops didn't know that.

**Comment by indigoviolet** [comment]
Should this option "Don't let pages steal the focus on loading" work on chrome extension pages as well?

 I find that it does not work for TabWrangler (https://chrome.google.com/webstore/detail/tab-wrangler/egnjhciaieeiiohknchakcodbpgjnchh?hl=en)'s "Tab Corral" page. Note that I have injected Vimium-C into TabWrangler (following https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions)

**Comment by gdh1995** [comment]
@indigoviolet Um currently injection does not support `grabBackFocus`. I'll add it in a next version.

**Comment by indigoviolet** [comment]
@gdh1995 Thank you!

**Comment by indigoviolet** [comment]
@gdh1995 sorry to necro-bump this issue - but I still find that the "Tab Corral" page mentioned [above](https://github.com/gdh1995/vimium-c/issues/164#issuecomment-814419118) is able to steal focus on loading, with the latest version of Vimium-C.

**Comment by gdh1995** [comment]
@indigoviolet Sorry I once forgot your question and didn't tell you about new usages. When you modify HTML of `Tab Corral`, now you may add some switches to change Vimium C's behaviors: https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions#useful-switches-of-injection . And in your case, `[data-block-focus]` should help.

**Comment by indigoviolet** [comment]
Thank you, that worked!
