### ISSUE TITLE
autoOpen command doesn't work properly when an IP address is selected

### ISSUE THREAD

**Issue by cyberhuman** [gdh1995/vimium-c#177]
Custom key mappings:
```
map Cf autoOpen keyword="foo"
```
Custom search engines:
```
foo: https://bar.com/%s Test
```
Selecting an IP address on a page, e.g. 1.2.3.4 and pressing `C`, then `f` opens a new tab with the IP address in the URL, not https://bar.com/1.2.3.4.

**Comment by gdh1995** [comment]
This works as designed: when the selected is a complete URL or a hostname, then `autoOpen` and many other commands won't use a search engine to build a new query URL.

For this case, I suggest you use `Vomnibar.activateUrl`, which loads current selected text as the initial query words, and then press <kbd>Home</kbd> to type a search engine keyword.

**Comment by cyberhuman** [comment]
Thank you for looking into this issue!
Too bad it's designed this way. I believe when a human tells the computer a keyword must be used, it must be used irrespective of what is selected. It's too "smart" and limiting for no reason.

**Comment by gdh1995** [comment]
Well, I can add a new option to disable this feature, but it will need a few weeks.

**Comment by cyberhuman** [comment]
That would be nice and I can wait of course. Thank you for all your hard work! 感谢你的辛苦！

**Comment by cyberhuman** [comment]
I found a bug in this "feature":
- trying to autoOpen an email address like `foo@bar.com` will use the keyword;
- trying to autoOpen an email address like `foo@bar.baz.com` will open `bar.baz.com` instead.

All in all, I don't understand why would anyone want this behaviour by default.

**Comment by gdh1995** [comment]
Oh this also works as I once intended.

Up to now, I make Vimium C try its best to recognize "hostnames", so there's a problem: how to tell mail addresses of `user@host` from plain strings of `user:password@host:port`. Then, if a `host` includes "mail" or only has a company ID and a top-level domain, Vimium C will treat it as a mail address.

**Comment by cyberhuman** [comment]
Too smart :-D

**Comment by gdh1995** [comment]
Hello, you may try this: [vimium_c-1.83.2-chrome-9041514.zip](https://github.com/gdh1995/vimium-c/files/4671136/vimium_c-1.83.2-chrome-9041514.zip), [vimium_c-1.83.2-firefox-9041514.zip](https://github.com/gdh1995/vimium-c/files/4671137/vimium_c-1.83.2-firefox-9041514.zip).

You may add this to key mappings: `map Cf autoOpen keyword="foo" testUrl=false`. If `keyword` exists, then `testUrl` is default to `false`; otherwise `testUrl` is default to `true`.

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`
