### ISSUE TITLE
the checkbox in datagrid could not be identified.

### ISSUE THREAD

**Issue by Mapleguoguo** [gdh1995/vimium-c#181]
we find that the checkbox could not be identified by press "f", details are as below

![1](https://user-images.githubusercontent.com/65766103/82788689-82374080-9e9b-11ea-82dd-448ef0832dea.png)

![2](https://user-images.githubusercontent.com/65766103/82788723-93804d00-9e9b-11ea-9fa0-ddf128bcedda.png)

**Comment by gdh1995** [comment]
What's the URL of the page?

Usually because the page doesn't follow HTML specifications and draw its own buttons and checkboxes using plain `<span>`s. Then it can not be fixed in a current version of Vimium C.

A new feature may be added in months, and with it you will be able to write host-specific CSS selectors for LinkHints to mark clickable elements.
