### ISSUE TITLE
Map key in visual/caret mode?

### ISSUE THREAD

**Issue by jlnbdt** [gdh1995/vimium-c#202]
Hi,

I use "bépo" french layout and letters c/t/s/r are mapped to scroll left/down/up/right.
But in visual and caret modes, I've to use the default h/j/k/l keys, which is not very convenient…
Is there any way to remap keys in visual and caret modes?

Thanks a lot.

**Comment by gdh1995** [comment]
Please try `mapKey` in custom key mappings.

(Refer: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout) **Since v1.80.1, this directive takes effects in all modes**, and any `mapKey=false` option won't be obeyed by Vimium C. This version also adds a feature of per-mode mapping. For example, `mapkey <f:o> <f2>` will only make `Vomnibar` treat `f` as `<f2>`, while not in others modes. In this example `o` means Vomnibar, and you can also use `i` (Insert Mode), `l` (LinkHints), `f` (FindMode), `v` (VisualMode) and `m` (Marks).

The usable keys in VisualMode are in https://github.com/philc/vimium/wiki/Visual-Mode.

**Comment by jlnbdt** [comment]
Work like a charm :-)
Thank you very much!
