### ISSUE TITLE
Feature request: OpenUrl and press 'f'

### ISSUE THREAD

**Issue by Zeioth** [gdh1995/vimium-c#218]
I think it's a case of use common enough to make it a command. In my case:

- I press gh to go home.
- I press F.
- I press the key combination to open the link.

I doesn't sound much of a hustle but it's something you repeat constantly. If you can save pressing f, would be nice.

**Extra**
If there was some way to make a page link remember its key combination forever would be nice for muscular memory, but I understand the difficulty of implementing this.

**Comment by gdh1995** [comment]
It's not easy to implement fixing hint characters. There're similar discussions about this in the original Vimium repo but all have gave up.

As for auto starting LinkHints, there're also similar discussions. Up to now I don't want to expose this API to normal pages, but maybe I'll add this feature to 3rd-party extensions which support Vimium C.

You may read https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions to get your desired new-tab extension to work with Vimium C. For example, I've modified "X New Tab" and published the result to https://chrome.google.com/webstore/detail/微度新标签页修改版/hdnehngglnbnehkfcidabjckinphnief (note it only has a Chinese UI).

**Comment by gdh1995** [comment]
Hello, now I remember there has been an exposed API to allow 3rd-party extensions to run LinkHints:
`VApi.f(2, { /* whatever options your want*/ m: 0 }, 1)` since the next released version of Vimium C (it will be v1.85.2).

Here's a simple script to load Vimium C in another extension's web page: https://github.com/gdh1995/vimium-c-helpers/blob/master/pdf-viewer/vimium-c-injector.js . And a normal way to trigger Vimium C commands is to call `VApi.f(cmd-id, options, count)` when Vimium C is ready.

* `VApi` is the only API interface exposed by Vimium C
* `VApi.f` refers to `focusAndRun`, and it can be used to run in-page commands
* the first argument is a command ID, and please use `kFgCmd.***` in it

https://github.com/gdh1995/vimium-c/blob/814cd1ef5c9961bcc33475e6ef11560c1da6b58a/typings/messages.d.ts#L191-L195

* the 2nd and 3rd argument is an object of command options and the repeating count since v1.85.2
  * Note: in v1.85.1 and before, the 2nd is count, while the 3rd is object

**Comment by gdh1995** [comment]
I'll close this issue since it's somehow inactive. If you have new questions or problems about this issue, feel free to reopen it.
