### ISSUE TITLE
Interference with other addons

### ISSUE THREAD

**Issue by CaioCMartinelli** [gdh1995/vimium-c#233]
Hello, I'm having compatibility problems with addons that use unique keys to execute commands in Firefox.

The biggest problem (the one that affects me most and i really care) is the "Video Speed Controller [1]", as the name says, a manager with media controls for any HTML5 video on web.

When using Vimium, it overlaps and completely prevents the HTML5 configured media buttons from working, is there anything that can be done to avoid this interference?

[1] https://addons.mozilla.org/pt-BR/firefox/addon/videospeed/
[1] https://github.com/codebicycle/videospeed

**Comment by gdh1995** [comment]
@CaioCMartinelli It seems due to keyboard focus changes. What about click the video area before you press shortcuts of "Video Speed Controller"?

Or you can disable "Don't let pages steal the focus in loading" on Vimium C Options page, and then try those keys again (without clicking the video area firstly).

Limited to some technology details, when this option is enabled, Vimium C (and Vimium-fx) has to grab focus since a page starts loading, and at that time it hasn't learnt it should be disabled on such a page. Maybe I can add some logic to recover its wanted focus state when Vimium C gets disabled, in recent months.

**Comment by gdh1995** [comment]
Oh I find the root cause.

You have used a wrong exclusion pattern and then Vimium C is not disabled on Youtube. If the URLs you see starts with `https://www.youtube.com/watch...`, then the pattern should be `:https://www.youtube.com/` .

Now that Vimium C is enabled, then even when there's `unmapAll`, Vimium C will still grab keyboard events. Therefore `0~9` and `-` will always be blocked, because Vimium C will treat them as "count prefixes of mapped keys".

**Comment by CaioCMartinelli** [comment]
Thanks for the help, it partially solved the issue.

It looked like this:

If I disable using the correct URL you mentioned, it works

If I disable the specific Vimium key, the other addon is able to receive the press information and work.

The problem that remains is if Vimium is active, none of the above 2 options works, disabling the site or unmapping the key, it does not let add-ons work using Numpad 1 ~ 9, it completely blocks them. From what you said I don't think there would be a possible solution, am I right?

Thanks

**Comment by gdh1995** [comment]
OK.

BTW, the usage of `:http://...` is only supported by Vimium C, while Vimium always treats patterns as "simplified" regexps, so you may use `https://www.youtube.com/*` on the Vimium Options page.

**Comment by CaioCMartinelli** [comment]
Yes i use Vimium-C only, thanks man, you are awesome.
