### ISSUE TITLE
feature request:  customization options for hint mode

### ISSUE THREAD

**Issue by gtusr** [gdh1995/vimium-c#264]
An option that would be nice to have in hint mode for links in a web page would be to choose whether to center the hint over the link or left/right align it.

Color, font, size and style options could be useful too.

**Comment by gdh1995** [comment]
Um, I think this is a very rare demand to customize hint positions, because in the original project of this repo, [Vimium](https://github.com/philc/vimium), there have been few requests about moving hints.

As for its color, fond and other styles, you may write CSS into "Custom CSS for Vimium C UI" on Vimium C Options page, and those styles will override Vimium C's default rules (both of them will follow CSS priority rules, and custom CSS will always be appended to default CSS).

**Comment by gdh1995** [comment]
Therefore, I'm sorry but I'm not interested in adding logic to moving hints right / down.
