### ISSUE TITLE
Suggestion: captureTab download button and whole page capture

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#274]
It would be nice if captureTab could capture an entire page from top to bottom even beyond the viewable area and then offer to select which part to save.
Also right now one has to right click the image and select save because in Firefox [download binding is not working](269)
so adding a Download button to the image toolbar can help.
Thank you

**Comment by gdh1995** [comment]
&nbsp;If there's a button to download,&nbsp; You still need a mouse click to activate it...



---Original---

**Comment by gdh1995** [comment]
As for full page capturing, this problem is not as simple as one may expect, because Chrome doesn't give such an API: I searched in Google, and found most articles suggests some specialized extensions to do so.

See https://stackoverflow.com/questions/8303327/taking-full-page-screenshot-with-a-chrome-extension

BTW, Firefox 82+ supports a new option to define the rect when capturing, but I haven't tested it. Even if it works, there's still no idea on Chrome.

**Comment by elig0n** [comment]
> &nbsp;If there's a button to download,&nbsp; You still need a mouse click to activate it...

I can get the link hints to activate just fine with the toolbar buttons 
![cut](https://user-images.githubusercontent.com/31196036/103531692-8a744700-4e92-11eb-80d7-5359deb18d7d.png)

**Comment by gdh1995** [comment]
Yes, but Firefox still refuses to show any download dialog for such click actions triggered by S/A/D/J/... .

**Comment by elig0n** [comment]
but it can open in new tab
