### ISSUE TITLE
Malfunction of Finding word in GitHub Jupyter notebook

### ISSUE THREAD

**Issue by BerginJay** [gdh1995/vimium-c#279]
打开github仓库中的jupyter notebook，使用"/"查找单词时，只能检索到页面内notebook外的单词，notebook内的单词无法检索到。

平台：Mac OS 10.15.7，浏览器：Firefox 84.0.1。[notebook 地址](https://github.com/marcharper/python-ternary/blob/master/examples/Ternary-Examples.ipynb)

When using "/" to find a word in jupyter notebook in GitHub, words can not be located within the notebook.

Platform: Mac OS 10.15.7, Browser: Firefox 84.0.1. [Notebook address](https://github.com/marcharper/python-ternary/blob/master/examples/Ternary-Examples.ipynb)

**Comment by gdh1995** [comment]
It because the notebook content is in an `<iframe>`

**Comment by gdh1995** [comment]
It because the notebook content is in an `<iframe>`, and `FindMode` can only search text in a current frame (in your case, there're two frames: the outer content and notebook).

The limit of searching inside a frame is designed to avoid complicated bugs which may occur in searching across frames, because: 1) browsers' find-in-page APIs are not well-designed; 2) different frames may have different security permissions, so extensions can not access all of them "on the same time".

Reference:
- iframe: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by BerginJay** [comment]
got it. thanks.
