### ISSUE TITLE
multiple modifier keys not working?

### ISSUE THREAD

**Issue by kovasap** [gdh1995/vimium-c#29]
map <a-c-j> moveTabLeft
map <a-c-k> moveTabRight

These commands don't seem to work here (they work for me in regular vimium).  Is there a better way to define them that will work?

**Comment by kovasap** [comment]
map \<a-c-j\> moveTabLeft
map \<a-c-k\> moveTabRight

**Comment by gdh1995** [comment]
Sorry, it's indeed a bug of Vimium C and has been fixed in latest code (not released yet).

When you use `map <a-c-j> ...` and then press Alt+Ctrl+J, the content script mistakenly generates `<c-a-j>`. What's worse is, on Vimium C Options page, you can not write `<c-a-j>` - it will be "normalized" into `<a-c-j>` by another part of code.

I'm fixing some other (old or recent) bugs and have a plan to release a new version in weeks (before Chrome 74 stable).

Besides, in the new version, the key syntax will change: `<a-J>` will be replaced with `<a-s-j>`, and old format will be auto translated for compatibility.

**Comment by kovasap** [comment]
ok, i tried using `<c-a-j>` as well, and that didn't work either for my mappings

**Comment by gdh1995** [comment]
Status update: Vimium C has released v1.74.* for a few weeks, so, is this issue solved or not?

**Comment by kovasap** [comment]
Yep, it works now!  Thanks.
