### ISSUE TITLE
usbank.com unsupported

### ISSUE THREAD

**Issue by kajukenbo** [gdh1995/vimium-c#296]
vimium-c seems to prevent login to online banking at usbank.com
Perhaps more testing is needed or a note to blacklist it?

**Comment by gdh1995** [comment]
Sorry for this issue. Do you mean you can not type username or password on the site?

Some websites use Javascript, WASM or even C++ plugins to create secret input boxes, in order to encrypt user actions, while it prevents Vimium C from learning what areas are input boxes and what're not. The difficulty to fix support for such a website may vary widely - from easy (add some code to recognize its input box) to impossible to fix (e.g. if a website uses a C++ plugin).

Usually, to work around this, you can turn off Vimium C once, by clicking Vimium C icon at the top-right corner of your browser window. Then it will show a popup dialog, and just click `Disable for once (X)` to keep Vimium C completely disabled on a current tab and until the tab is closed / refreshed. 
* When a page is disabled, you can also open the popup again and click `Enable for once` (or `Reset`) to re-enable Vimium C.
* Or you can add a key mapping to disable or enable Vimium C, like:
  * `map <a-/> openUrl url="vimium://status/toggle-disabled/^\u0020<a-/>"`

For more detailed usages, please see https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut .
