### ISSUE TITLE
[Feature request] Display hints to enter visual/caret mode

### ISSUE THREAD

**Issue by ivanddm** [gdh1995/vimium-c#3]
I really like Chrome and Vimium. However right now I am using Firefox due to Vimfx. One of the reasons is that I use visual mode quite frequently and I find the implementation of caret/visual mode much easier in vimfx than in vimium (also now available in surfingkeys for chrome).

By hitting `v`, Vimfx first displays hints just like when you hit `f`, which allows to you go right away to the sentence, box, or sometimes word that you want to highlight in visual mode, which I find it extremely faster and convenient over searching for a keyword first and then enter visual mode in vimium.

It would be great if this feature could implemented, of course if you like the idea. Thanks in advance.

**Comment by gdh1995** [comment]
Sorry for my silence during these days.

I tried `v` in `VimFx` last week, and it does benefit users.

But I find this feature needs too many efforts to implement it. Please be more patient. Thanks.

**Comment by idd79** [comment]
Hi and thanks for replying. I understand that this feature should be difficult to implement, but it would be great seeing in Vimium at some point. Thanks again for your efforts with this. Take care!

**Comment by Monirzadeh** [comment]
hi
do you have any progress on this issue?

**Comment by gdh1995** [comment]
No progress and no plans in recent months.

**Comment by gdh1995** [comment]
Hello all, here's a fresh version supporting `LinkHints.activateModeToSelect`: [vimium_c-1.85.2-chrome-3b4bc8a.zip](https://github.com/gdh1995/vimium-c/files/5250148/vimium_c-1.85.2-chrome-3b4bc8a.zip) and you may take a try

It also supports a command option of `caret=true`, to enter the caret mode, instead of visual mode.

@ivanddm @Monirzadeh

**Comment by ivanddm** [comment]
Yes Sir!

I just tried it out and it is working quite nicely actually, just like Surfingkeys! Going to use it for some days and will report back to you if anything. I always wanted to use Vimium instead of Surfingkeys, but the lack of this feature stopped me from doing so, now it looks like I finally can 😄 .

Thanks a lot for this!

**Comment by ivanddm** [comment]
I'm closing this as your solution is working like a charm. Three days in a row of using Vimium-C and didn't find any issues what so ever with this feature.

Thanks again!

**Comment by ivanddm** [comment]
I forgot to ask you. Will you be pushing these new features (`LinkHints.activateModeToSelect` and CSS option to display the Vomnibar) to your official Chrome extension?

**Comment by gdh1995** [comment]
In my plan, in the next weekend I will publish a new version including this command.

On the last weekend I spent some time in solving crashes of VisualMode on Firefox. It seems Firefox has changed how selection works since one year ago. While although some found crashes are solved, VisualMode may still have to exit in quite a few situations.
