### ISSUE TITLE
Open the page, and soon, the key changes

### ISSUE THREAD

**Issue by zhouyangnk** [gdh1995/vimium-c#304]
![1](https://user-images.githubusercontent.com/10472264/110668839-b00d2c00-8206-11eb-90f6-a8c9196203f9.gif)

This problem occurs on specific web pages, such as zhihu.com,how can I fix it? Thank you.

**Comment by gdh1995** [comment]
This is a feature: auto re-activate if "host scripts in a page marks some plain elements clickable (by adding click listeners)" and:
1. LinkHints was activated when a page was still in loading
2. LinkHints was just activated ("just" means no letter prefix has been typed).

The auto re-activation will only happen once during page loading (on `DOMContentLoaded` event). Then I suggest that you may wait for a while when a page is not ready.

There's also another auto re-activation when LinkHints get some letters and clicks an element in queue mode. LinkHints checks position of the last clicked element in about 300ms, and if it has moved or hid, then LinkHints will re-activate, in order to show marks for newly visible elements like dialog elements.

**Comment by zhouyangnk** [comment]
Thank you for your detailed reply.

Will it be possible to provide an option for users to set whether to enable this feature in the future? 
Or for ease of use, vimium-c keep the old keys unchanged when re-activation? 

Thanks again.

**Comment by gdh1995** [comment]
Well, I'll add a command option to skip it.

It's too complicated to keep letters for "old" elements.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.0 has been released on Firefox Add-ons, and being verifying by Chrome Web Store and MS Edge Add-ons. So you may take a try.

Now `LinkHints.activateMode` has a new option named `autoReload`, and if it exists it will determine in which cases Vimium C will auto reload.

`autoReload` can be `"click"`, `pageload` or `"click,pageLoad"` (ignoring case). So for this issue I suggest you try `autoReload="click"`.

**Comment by zhouyangnk** [comment]
Thank you!
My Edge Vimium C updated to 1.89.0, but I did not find any option named LinkHints.activateMode or autoReload in Vimium C's options page, Are there any other steps I missed?
![1](https://user-images.githubusercontent.com/10472264/114564716-2b00b100-9ca3-11eb-9fdb-922ce3455660.png)

**Comment by gdh1995** [comment]
um，add the line to 'custom key mappings'



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 13, 2021 21:58 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Open the page, and soon, the key changes (#304)




 
Thank you!
 My Edge Vimium C updated to 1.89.0, but I did not find any option named LinkHints.activateMode or autoReload in Vimium C's options page, Are there any other steps I missed?

**Comment by gdh1995** [comment]
add:


map f&nbsp;LinkHints.activateMode autoReload="none"



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 13, 2021 21:58 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Open the page, and soon, the key changes (#304)




 
Thank you!
 My Edge Vimium C updated to 1.89.0, but I did not find any option named LinkHints.activateMode or autoReload in Vimium C's options page, Are there any other steps I missed?

**Comment by zhouyangnk** [comment]
Sorry, I misunderstood before.
I set autoReload="click" and it works fine!
Thanks again!
