### ISSUE TITLE
About Find-In-Page

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#318]
1.  In other extensions' standalone windows:

![截图4](https://user-images.githubusercontent.com/66708845/113469706-5f45c780-9482-11eb-9756-e76ac31db521.png)
![截图5](https://user-images.githubusercontent.com/66708845/113469708-6076f480-9482-11eb-94af-4db429f8fbd6.png)

the amounts of the results of Vimium-C's and Chrome's are significantly different, but when hitting _n_ (next result) Vimium-C still match as much as Chrome's.

2. In some PDF viewer extension([https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?utm_source=chrome-ntp-icon](url))'s browser page of file content, matches' color is too mild and are always at the bottom of screen while it's better off to be at the middle:

![屏幕截图(252)](https://user-images.githubusercontent.com/66708845/113470187-39222680-9486-11eb-8730-020bd6d319e6.png)

3. Still in PDF viewer: although being opened, only the already loaded content is what the search take account of. It would be better to actively load the rest content and do a more complete search. I know they have their own Find-In-Page, but they have no supports for regexp.

**Comment by gdh1995** [comment]
The count number is very hard to calculate, and only your browser itself is able to get it. The result Vimium C gets is from text in webpage HTML content - text in editable boxes and shadow DOMs is "not accessible" when counting. When `n`, Vimium C calls a browser API to "find a next occurrence", so it works well.

And, in your screen snapshot. the page uses [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) and then Vimium C only reads `沪江小D`.

The color is "the original color with opacity=0.2", and the 0.2 is from PDF Viewer itself. It seems impossible to solve this incompatibility.

Vimium C won't scroll a page if a current occurence is visible. This is to avoid page jittering.

This is also very hard to implement. The PDF Viewer only renders visible parts of a PDF file in order to save memory and CPU, which prevents your browser from knowing the full text . If someone wants to fix this problem, then I suggest adding RegExp support to PDF Viewer's Find-In-Page ...

BTW, your link of PDF Viewer extension seems wrong. `PDF Viewer for Vimium C` is in https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj .

**Comment by OnceThenEver** [comment]
Alright, I'll work around them.
