### ISSUE TITLE
I cannot focus links using link hints

### ISSUE THREAD

**Issue by septsea** [gdh1995/vimium-c#319]
I want to focus links by adding the custom key mapping:

```
map e LinkHints.activateMode action=focus
```

However, it does not work. Is there any workaround?

**Comment by septsea** [comment]
This is my settings.

![image](https://user-images.githubusercontent.com/57337516/113549129-7243cd80-9623-11eb-80f7-4f81ce9d8be8.png)

I do not know why the first line is replaced by

```
map e LinkHints.activateMode action="focus"
```

Maybe this causes the feature unable to work?

**Comment by gdh1995** [comment]
Why did you think it failed? With `map e LinkHints.activateMode action="focus"`, <kbd>e</kbd> will show hint marks for text boxes, buttons and links, and then you can select and focus an element by typing characters of a mark:

![image](https://user-images.githubusercontent.com/5547703/113572314-9070f400-964a-11eb-833f-7a8bab67b695.png)

BTW, the replacement is a feature of auto-correcting key mappings. The valid syntax is `"map" key-sequence command-name option1-name=<JSON>`. So `focus` was replaced by `"focus"`.

**Comment by septsea** [comment]
@gdh1995 Thanks for your reply.

Well, in my opinion, focusing a link does not open it.

To be precise, I want to focus a link without actually opening it. With the key mapping, `e` still opens the link in the current tab. Maybe this is a feature instead of a bug?

**Comment by septsea** [comment]
My not-so-satisfying workaround is to open the link in a new tab using `F`.

**Comment by gdh1995** [comment]
&nbsp;Does your "e" open links on Vimium C options page?


&nbsp;If it does, then it's a bug. Or, on what page and what links did you find this problem?



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 5, 2021 20:38 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] I cannot focus links using link hints (#319)




 
@gdh1995 Thanks for your reply.
 
Well, in my opinion, focusing a link does not open it.
 
To be precise, I want to focus a link without actually opening it. With the key mapping, e still opens the link in the current tab. Maybe this is a feature instead of a bug?

**Comment by septsea** [comment]
Yes.

Both Edge and Firefox fail in focusing links without opening them.

All pages. All links. When I press `e`, `Open link in current tab` is displayed at the bottom right corner(?).

Moreover, the same problem occurs as well even if `"focus"` is replaced by `"hover"`.

**Comment by gdh1995** [comment]
Um, sad - confirmed this is a bug. I'll fix it in days.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.0 has been released on Firefox Add-ons, and being verifying by Chrome Web Store and MS Edge Add-ons. So you may take a try.

**Comment by septsea** [comment]
Good morning. Thank you very much! It works well on most pages that I often visit.
