### ISSUE TITLE
youtube thumbnail hover instead of click them

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#327]
youtube show a short part of video if you hover mouse on thumbnails. this feature make that hard to use vimium-c in youtube.
Current behavior
1. open youtube
2.  press 'f' 
3. hint on thumbnail
4. it play thumbnail short preview instead open link
5. do again step 2-3-4 to open that video

expected behavior
1. open yourube
2.  press 'f' 
3. hint on thumbnail 
4. open video

i know it is not a problem in vimium-c but, is it possible to handle that?(without disable this function completely)

**Comment by gdh1995** [comment]
`map f LinkHints.activateMode touch="auto" clickable="#thumbnail"`

Or for more complicated mappings:
```
env youtube host="https://www.youtube.com/"
map f runKey expect={"youtube":"<v-ytf>"} keys="<v-f>"
map <v-ytf> LinkHints.activateMode clickable="#thumbnail"
map <v-f> LinkHints.activateMode
```

**Comment by OnceThenEver** [comment]
@gdh1995 I saw you proposed `LinkHints.activeMode` several times but I never met this at help panel.

**Comment by gdh1995** [comment]
um, it should be LinkHints.activate, but not .active


and the tail "mode" can be omitted.



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 13, 2021 18:24 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] youtube thumbnail hover instead of click them (#327)




 
@gdh1995 I saw you proposed LinkHints.activeMode several times but I never met this at help panel.

**Comment by OnceThenEver** [comment]
alright

**Comment by Monirzadeh** [comment]
thanks it's work fine
