### ISSUE TITLE
Unable to delete some history items from vomnibar "This item cannot be deleted"

### ISSUE THREAD

**Issue by CarbonChauvinist** [gdh1995/vimium-c#347]
When I try and delete some history from the vomnibar (by highlighting and using "shift+delete") I'm unable to for some items.

I receive a message stating "This item cannot be deleted", however, other items are able to be deleted -- "succeeded to delete a history item"-- I can't determine what allows me to delete one item but not another, it appears to be arbitrary. 

It does appear that recent history items are unable to be deleted, but older ones are? 

I'm also using firefox-sync daemon which syncs my profile to tmpfs -- not sure if that's the cause. Anything I can do to troubleshoot further?

**Comment by gdh1995** [comment]
Yes "recent" history items can not be deleted, because in fact they're not "history records" but "recently closed sessions", and the later can only be listed and "restored" as normal tabs by the `browser.sessions` API (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions).

You may tell such items from normal history ones by watching their tail labels next to titles:

![image](https://user-images.githubusercontent.com/5547703/118609657-887da580-b7ed-11eb-8d5f-cecd23534b72.png)

**Comment by CarbonChauvinist** [comment]
Interesting, thanks for the detailed response (and fantastic tool). 

What is the threshold whereby a closed session becomes a history record? Is there a way for me to manipulate that threshold in any way? Or does it simply pertain to closing and re-opening firefox and thereby starting a new session?

It also looks like there are forget methods associated with closed sessions. Could vimium-c detect if the highlighted entry in the vomnibar is of a closed session type and use the forget method instead of attempting to delete a history record when appropriate? Does that even make sense?

Thanks again.

**Comment by gdh1995** [comment]
The number of closed sessions should be 25,&nbsp; which is constant for web extensions. And I haven'tfound any way to modify such a number in the browser settings.


I haven't found any API to "forget" a closed session item. Why do you think so? Could you provide a document for it?



---Original---
From: ***@***.***&gt;
Date: Tue, May 18, 2021 21:30 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Unable to delete some history items from vomnibar "This item cannot be deleted" (#347)




 
Interesting, thanks for the detailed response (and fantastic tool).
 
What is the threshold whereby a closed session becomes a history record? Is there a way for me to manipulate that threshold in any way? Or does it simply pertain to closing and re-opening firefox and thereby starting a new session?
 
It also looks like there are forget methods associated with closed sessions. Could vimium-c detect if the highlighted entry in the vomnibar is of a closed session type and use the forget method instead of attempting to delete a history record when appropriate? Does that even make sense?
 
Thanks again.

**Comment by CarbonChauvinist** [comment]
I see, I'm most likely misreading/misunderstanding what's going on, but I was referring to [sessions.forgetClosedTab()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/forgetClosedTab) function from your link

**Comment by gdh1995** [comment]
ok, it seems not existing on Chrome.


Then I'll update code to allow deleting on Firefox.



---Original---
From: ***@***.***&gt;
Date: Wed, May 19, 2021 10:15 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Unable to delete some history items from vomnibar "This item cannot be deleted" (#347)




 
I see, I'm most likely misreading/misunderstanding what's going on, but I was referring to sessions.forgetClosedTab() function from your link

**Comment by CarbonChauvinist** [comment]
Just got the latest update, 1.90.0, and was able to successfully delete a closed session item from the vomnibar in FF. Thanks so much for considering and implementing this useful feature.

**Comment by foxjaw** [comment]
Sorry for the noob question. How to perform session history deletion on chrome ? Clearing history does not remove vomnibar list. Spooks me as hell !

**Comment by gdh1995** [comment]
You may try removing its history item on `chrome://history`:
![Uploading image.png…]()

**Comment by gdh1995** [comment]
You may try removing its history item on `chrome://history`:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/2ea77697-b8b3-43b4-b62e-75303f7741e4)
