### ISSUE TITLE
f/F does not always obey firefox container for current tab

### ISSUE THREAD

**Issue by falolaf** [gdh1995/vimium-c#351]
I use containers in firefox with e.g. this addon:
https://addons.mozilla.org/sv-SE/firefox/addon/temporary-containers/

Sometimes when a tab is opened in a container and I follow a link on that page which opens a new tab, with f or F, the link is opened in a non container tab. If I, with the mouse, either click or ctrl-click the link is opened in the same container as the current tab.

This seems to happen all the time with links on slashdot.org.

I have reproduced this with a new FF profile with only Vimuim-C and Temporary containers added.

Is this something that can be changed?

**Comment by gdh1995** [comment]
There're commands like `LinkHints.activateModeToOpenInNewTab`, or you may specify `newtab="force"`, but on Firefox both of these ways won't follow container settings, which is limited by Firefox's popup blocker (up to now).

**Comment by falolaf** [comment]
Thank you for your feedback!

I think I just leave it as is for the moment as some links actually work when a new tab is opened with F.

**Comment by falolaf** [comment]
I just now tried out Vimium-FF (https://github.com/philc/vimium) and it actually works with f/F for those links. I.e. link is opened in the same container. So, what is the difference?

**Comment by gdh1995** [comment]
Could you give an example of web pages on which Vimium C has this issue?

Vimium C correctly follows the web specification about `<a rel="noopener"></a>`, but this may prevent a new tab from locating in a same container.

While Vimium-FF (aka. Vimium) always set a new tab's opener to the current (old) tab, so it bypasses this issue.

**Comment by gdh1995** [comment]
BTW, if you re-map `LinkHints.activate` with `opener=true`, then Vimium C can ignore `[rel=noopener]`, and such a rule may look like
```
map f LinkHints.activate opener
```

**Comment by gdh1995** [comment]
BTW, if you re-map `LinkHints.activate` with `opener=true`, then Vimium C can ignore `[rel=noopener]`, and such a rule may look like
```
map f LinkHints.activate opener
```

**Comment by falolaf** [comment]
Most of the links, for the articles, on this page works in Vimium but not in Vimium C:
https://slashdot.org/
(I have not tested them all...)

`map f LinkHints.activate opener`
seem to work but:
`map F LinkHints.activate opener`
does not open links in new tab if the link is not set to open a new tab.

I.e. links on:
http://lxer.com/
does not open in new tab if above mapping is used.

After some more testing this maping seem to work as I want:
`map F LinkHints.activateModeToOpenInNewTab opener`

I will use that for a while and see if it is ok in the long run.

**Comment by gdh1995** [comment]
Thanks, and I'll take a look at such pages.

In the mapping above, `f` or `F` won't affect how LinkHints works, since the 2 lines has a same option list (only `opener`). If you need to force links to open in a new tab, then `LinkHints.activateModeToOpenInNewTab` and `LinkHints.activateModeToOpenInNewForegroundTab` do help, because they indicates LinkHints should in new-tab modes.

**Comment by falolaf** [comment]
Thank you for your investigations @gdh1995! Very much appreciated.

I have ended up with only this mapping:
`map f LinkHints.active opener`
because if using `f` and then type any of the letters for the hint as capital, then the link will be opened in a new background tab and in same container. This way of working suites me fine. I learnt that in another thread somewhere.

**Comment by gdh1995** [comment]
Hello.
I rechecked how Firefox and Chrome handles rel=noopener, and was surprised at that the rel won't affect "Tab.openerTabId" and this value always exists on ctrl-click.
Thereforr I decided to ignore the _blank and rel, and change the default value of "opener" to true, so that it can work better by default.
And then the default position of a new child tab will be next to previously-opened child tabs.



---Original---
From: "Anders ***@***.***&gt;
Date: Mon, May 31, 2021 12:01 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] f/F does not always obey firefox container for current tab (#351)




 
Thank you for your investigations @gdh1995! Very much appreciated.
 
I have ended up with only this mapping:
 map f LinkHints.active opener
 because if using f and then type any of the letters for the hint as capital, then the link will be opened in a new background tab and in same container. This way of working suites me fine. I learnt that in another thread somewhere.

**Comment by gdh1995** [comment]
V1.90.2 has been released on Firefox, so if you enable the optional `cookies: only for contextual info to work with Multi-Account Containers"` permission, then Vimium C can learn container info, so newly-opened tabs will usually keep in a same container, unless finding an option of `group=false`, or they're extension pages.

**Comment by falolaf** [comment]
I noticed that option after the new version was installed and I was wondering what it was all about. Thank you @gdh1995!
