### ISSUE TITLE
H not going back in Firefox since upgrading to 1.90.0

### ISSUE THREAD

**Issue by shosti** [gdh1995/vimium-c#353]
Since upgrading to 1.90.0, the "H" key no longer seems to work for going back (oddly "L" works fine for going forward). I confirmed that the key mappings are correct, and that "H" still works with vimium-ff.

**Comment by meluskyc** [comment]
Also breaking in Chrome for me since upgrading to 1.90.0.

**Comment by gdh1995** [comment]
confirmed.


Please use "map H goBack count=-1" to work around this bug.


I'll wait for some other bug reports about v1.90.0, and publish v1.90.1 after fixing them.



---Original---
From: "Emanuel ***@***.***&gt;
Date: Wed, May 26, 2021 03:11 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] H not going back in Firefox since upgrading to 1.90.0 (#353)




 
Since upgrading to 1.90.0, the "H" key no longer seems to work for going back (oddly "L" works fine for going forward). I confirmed that the key mappings are correct, and that "H" still works with vimium-ff.

**Comment by copergopher934** [comment]
Not to hijack this thread because I don’t know if it’s worth a seperate issue, but the help/shortcuts dialog stopped following the ui.systemUsesDarkTheme parameter on FF88 on some websites since the update (i.g. on github it works just as usual, whereas on youtube, reddit and wikipedia, it doesn’t).

**Comment by gdh1995** [comment]
For the problem of `H`: v1.90.1 has been published on Firefox and Chrome stores, so the default `map H goBack` should work well.

While `map H goBack count=-1` will work like a `goForward` on v1.90.1, so it's necessary to remove the `count=-1` option.

A better way to work on both v1.90.1 and v1.90.0 is: `map H goBack $count=-1`.

**Comment by gdh1995** [comment]
@copergopher934 confirmed it's a typo bug. Thank you for this report.

**Comment by meluskyc** [comment]
Confirmed v1.90.1 fixes the H issue. Thanks.
