### ISSUE TITLE
The "mouseenter" event is emitted by LinkHints

### ISSUE THREAD

**Issue by Delgan** [gdh1995/vimium-c#356]
Hi! Thank you for the work you put into maintaining this extension, it is life changing. :+1: 

I noticed though a compatibility problem with some of my JS scripts. While selecting an element with `f` and then `<key>`, then the `"mouseenter"` Javascript event is emitted while the mouse is not actually over the element. This is a problem because the `"mouseleave"` event is never emitted while selecting another element. Consequently, some of my scripts make wrong assumptions.

I'm using Firefox 87.0 with Vimium-C 1.90.1.
To reproduce the issue, go on https://github.com/gdh1995/vimium-c page, open console and type:

```javascript
let content = document.getElementsByClassName("repository-content")[0];
content.addEventListener("mouseenter", function() {console.log("Enter");});
content.addEventListener("mouseleave", function() {console.log("Leave");});
```
Put your mouse outside the files list. Then press `f` and select the drop-down list containing the repository branch name. You'll see `"Enter"` in the console logs. Select the "Search" input in the header. The  `"Leave"` message never appear in the console.

I compared with `vimium-ff` and the `"mouseenter"` event is not emitted while selecting elements. I guess it makes sense, as the mouse is not moving. Is there a particular reason why this event is emitted using `vimium-c`?

**Comment by gdh1995** [comment]
There should have been `mouseleave` events. I'll do tests to find why - maybe this means a bug.

**Comment by Delgan** [comment]
Thanks for the quick answer. Out of curiosity, why does Vimium need to emit the `"mouseenter"` event? This event is not emitted while focusing elements using Tab key for example, which seems pretty similar to Vimium `f`-selection.

**Comment by gdh1995** [comment]
I want to simulate "mouse" completely - in fact, Vimium C can even dispatch `touchstart`/`touchend` in LinkHints mode if with a command option of `touch=true|"auto"`.

It can simulate right click by `button="right"`, double click by `dblclick=true` and auto unhovering by `autoUnhover=true`.

It also simulates focusing changing, creates its `MouseEvent.sourceCapabilities` instance, and follows the `disabled` status of buttons/inputs. Since v1.90.0, it begins to simulate effects of a real mouse clicking on `<video>` and `<audio>`, if only there's no `interact=false`.

**Comment by Delgan** [comment]
That's pretty impressive, thanks for the details. Surely it makes sense, as the web is evolving more and more towards frameworks based on dynamic interactions. 

So I guess the `"mouseleave"` event should be emitted whenever we press `Escape` or select another element. Not sure what should happened when the mouse is actually moved, though.

**Comment by gdh1995** [comment]
`mouseenter` itself is imported by commit 98300586480c821ff15d89976d23aede5996be10 : On GitHub's issue details page, an avatar box receives mouseover/mouseleave events.

**Comment by gdh1995** [comment]
Hello, please try this version: [vimium_c-1.90.1-firefox-ea40d64.zip](https://github.com/gdh1995/vimium-c/files/6564662/vimium_c-1.90.1-firefox-ea40d64.zip) (usage: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package )

**Comment by Delgan** [comment]
@gdh1995 Thank you for this incredibly quick fix! It seems the `"mouseenter"` event is no longer emitted when I select a drop-down list. Consequently, it fixed the problem I had with some of my scripts. :+1:

**Comment by gdh1995** [comment]
&nbsp;Um, what I expected was: it would dispatch 'mouseleave' for disappearing elements (the old Vimium C doesn't), so it can notify your script in time.
I'm not sure why 'mouseenter' disappears.&nbsp; Maybe it's because I just fixed another issue about the 'bubbles' property of mouseenter/mouseleave events.

In fact, a browser has&nbsp;its own stack of mouse enter and mouse leave, and whenever you move a mouse, it dispatches tons of such events.&nbsp; While Vimium C only depends two of them - only on the target element, but not on its ancestors - to reduce CPU cost and response time.
&nbsp;I hope this would not cause too many differences.



---Original---
From: ***@***.***&gt;
Date: Sat, May 29, 2021 21:06 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] The "mouseenter" event is emitted while selecting elements with Vimium shortcut (#356)




 
@gdh1995 Thank you for this incredibly quick fix! It seems the "mouseenter" event is no longer emitted when I select a drop-down list. Consequently, it fixed the problem I had with some of my scripts. 👍

**Comment by Delgan** [comment]
@gdh1995 Ok, I tested on the Github page with the example I had first given. Indeed, now `"mouseeneter"` and `"mouseleave"` are both correctly emitted! The behavior you changed is much more intuitive. Thanks.

Actually, my example was wrong. The Github page is a bit special because it is not a real `<select>` element.

Here is a page where you can reproduce the problem I had while first opening this issue: https://htmlreference.io/element/select/#select

Type this in the console:
```js
let content = document.getElementById("select-example-0");
content.addEventListener("mouseenter", function() {console.log("Enter");});
content.addEventListener("mouseleave", function() {console.log("Leave");});
```

Before your fix, selecting the drop-down list would emit the `"mouseenter"` but `"mouseleave"` was never emitted. Now, it doesn't emit the `"mouseenter"` while selecting the list. I don't know if this is the behavior you expected, but at least it works fine in my case.

**Comment by gdh1995** [comment]
Well, this change is because I fixes `mouseenterEvent.bubbles` - it should be `false` and then your listener won't grab it. The old code mistakenly set it `true`.

If with:
``` javascript
let content = document.getElementById("select-example-0");
content.addEventListener("mouseenter", function() {console.log("Enter");}, true);
content.addEventListener("mouseleave", function() {console.log("Leave");}, true);
```

Then you'll still see both of them.

**Comment by Delgan** [comment]
Ok, great. Thanks for the explanation. Two fixes in one, then! :+1:

**Comment by gdh1995** [comment]
Hello, v1.90.2 for Firefox has been released and you may take a try.

**Comment by Delgan** [comment]
It works fine. Thanks for the quick release!
