### ISSUE TITLE
Declaration for Applicable Regions?

### ISSUE THREAD

**Issue by gqqnbig** [gdh1995/vimium-c#359]
When talking about China and Taiwan, why The Constitution of the People's Republic of China is referenced instead of [The Constitution of the Republic of China](https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=A0000001)? The latter demands China mainland is an inalienable part of the sacred territory of the Republic of China. 

The contributors to this repo are not only Chinese. As an American, I feel choked reading this repo as I may need to observe Taiwan Relations Act. 

I conjecture the source code of the software has no references to "Taiwan". Consequently, I don't think it's really necessary to have Declaration for Applicable Regions on README. After all, it is the publisher's call on ticking the applicable regions. The MIT license of the repo does not limit how people could publish it, right?

I'm expressing my concern. If your region or situation mandates that, I'm sorry for that. Vimium-c is a good software otherwise. Thank you, gdh1995 and other contributors.

**Comment by gdh1995** [comment]
The People's Republic of China is a formal member of the United Nations[1][2], while Taiwan's regime is neither a member of UN, nor recognized by most of foreign governments.

The main part of Vimium C's source code is added (and rewritten) by me, and I live in China. The declaration in README.md is made by myself, because I saw Chrome Web Store (and other stores) lists country names mistakenly:
* The correct way to list country names is to use `China (mainland)` and `China (Taiwan)`
* To say the least, it can use something like `PRC (China)` and `Taiwan (China)`.
* I DO NOT accept the current name list which only writes `Taiwan` and `China`

The wrong list is hurting all people in China and broadcasting wrong information to the public.

References:
1. https://www.un.org/about-us/member-states
2. https://en.wikipedia.org/wiki/China_and_the_United_Nations

**Comment by gqqnbig** [comment]
I'm sure you want to express your China concern to Chrome Web Store and other platforms since they are [Hurting the feelings of the Chinese people](https://en.wikipedia.org/wiki/Hurting_the_feelings_of_the_Chinese_people).

I fail to see such declaration on https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg . I guess the store page has more viewers than this repo and the store page has a stronger relation to your China concern. 

What do you if you move the declaration to the store page?

**Comment by gdh1995** [comment]
Yes there's a page for extension developers to decide into what regions an extension will be distributed.

![image](https://user-images.githubusercontent.com/5547703/120417296-30b87000-c391-11eb-97d6-dc359e9d579f.png)

Thanks for your idea. I'll add this declaration to the description section in extension stores, in a few future versions.

**Comment by gqqnbig** [comment]
May I ask a totally irrelevant question? I'm just curious what you guys think.

![iphone_label](https://user-images.githubusercontent.com/614159/121444849-d50a6a00-c9c2-11eb-977f-cccf09002b39.jpg)

Apple writes this line on every iPhone, "‘Designed by Apple in California. Assembled in China".

As a Californian, Apple looks like a separatist promoting California is a country. 

Do you view listing California and China together as dwarfing China or gainting California?

**Comment by gdh1995** [comment]
1. It's a common usage to say state/province names directly in "a same country" and names of foreign countries
2. Only an assumption: If amounts of people in the State of California attempt to claim "California is a country" in common websites, then I will also agree that such an image offends the public in the USA.
