### ISSUE TITLE
[Question] How to hide the key in search engines?

### ISSUE THREAD

**Issue by GiancarloAparicio** [gdh1995/vimium-c#379]
Hi personally I love this extension but they asked me if there is a way to use a search engine without the need to put the key in the input and just have a clean input and the 'display-name' below

![image](https://user-images.githubusercontent.com/61440825/123891980-5ba9cb80-d91f-11eb-950f-f4d279029f26.png)

Something like the behavior of vimium

![image](https://user-images.githubusercontent.com/61440825/123892342-06ba8500-d920-11eb-9703-2e059d491567.png)

I have this shortcut configured but the key still appears in the input :(
```
map <a-y> Vomnibar.activateInNewTab icase keyword="yt"
```

**Comment by gdh1995** [comment]
No there's no such feature to hide keyword. I don't like it because I often need to modify not query words but the keyword itself, mostly among Bing, Google and Bing Dict.

For example, when Vomnibar is open, type a word you have searched for using Vimium C, and press <kbd>ArrowDown</kbd> to select it, and then you'll see its search engine and query words in Vomnibar input, so you can edit it and do another search conveniently.

**Comment by GiancarloAparicio** [comment]
Thanks for taking the time to answer, I had not thought of it that way, but it will be a matter of getting used to it.
