### ISSUE TITLE
can not map only number keys?

### ISSUE THREAD

**Issue by doingnothing** [gdh1995/vimium-c#40]
It's ok to map special characters like !,@,#, or mixed group like q2,q1, but I can't figure out how to map only one number key like 1,2,
Could anybody help?
Thanks!

**Comment by gdh1995** [comment]
Not allowed in Vimium C currently.

Up to now, I think this feature is confusing and do not like it. If there's any idea to allow users to tell from count prefixes and number shortcuts easily, I may implement it.

PS: this issue was also mentioned in https://github.com/gdh1995/vimium-c/issues/10#issuecomment-488915287 .

**Comment by doingnothing** [comment]
有点不懂你的意思，在Command Listing里，现在还没有任何命令有数字开头呀？像各种双键有g开头的命令就自动抵消了单独g键的命令（用户不能把单独g设定了）。那么开放设定单独数字键好像不会令用户误会吧？

**Comment by gdh1995** [comment]
比如"3x" 会关闭3个标签页，"11x" 则关闭11个，如果右边不够多还会往当前标签页的左边找。

绝大多数命令都有数字前缀来做更多/不同的事情。而且，Vimium C还支持负数的数字前缀，用来改变命令重复执行的方向或者别的什么，相当于一个更灵活的命令参数。

**Comment by doingnothing** [comment]
哦原來如此複雜，明白了，謝謝🙏

**Comment by gdh1995** [comment]
设计如此，如果您没有新想法的话，请问可否关闭这个issue了？

Vimium C does this as intented, so may this issue be closed?

**Comment by gdh1995** [comment]
更新：去年实现了`mapkey`，所以可以映射数字键了，办法是：
```
mapkey 2 <fake2>
map <fake2> .....
```

也就是把`2`变成一个不是数字的虚拟键，然后绑定命令到这个虚拟出来的键上。缺点是没法用`2`做数字前缀了。

在计划的 v1.81.4 中，将支持：
```
mapkey 2 <fake2>
mapkey <2:e> 2
```

作用是，当`2`是第一个键时，视为`<fake2>`这个键；如果已经按下了某个数字前缀或者命令前缀，仍然当`2`处理。
