### ISSUE TITLE
[input box] Vimium-C command isn't usable in WhatsApp Web chatbox

### ISSUE THREAD

**Issue by jamestansx** [gdh1995/vimium-c#400]
**Describe the bug**
In [WhatsApp Web](https://web.whatsapp.com/), if the chatbox is focused, vimium-c isn't able to be triggered again unless using the mouse to click on any place to allow vimium-c gaining focus again. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL [WhatsApp Web](https://web.whatsapp.com/)
2. Click on any chat
3. `gi` to the chatbox
4. try to `esc`
5. nothing will happen like how other input boxes will be escaped
6. click on any blank place in the page
7. try `esc` again
8. the vimium c command is usable again

**Browser, OS and Vimium C version**

Browser: Edge 92.0.902.67 
OS: windows 10 21h1
Vimium C: 1.90.2

**Comment by gdh1995** [comment]
Please try this: https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box .

**Comment by jamestansx** [comment]
> Please try this: https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box .

Yes, I tried based on the [wiki page](https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box). However, the problem persists.

**Comment by gdh1995** [comment]
um, why was this closed? not reproduced since v1.92.0 ?



---Original---
From: "James ***@***.***&gt;
Date: Mon, Aug 9, 2021 15:07 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] [input box] Vimium-C command isn't usable in WhatsApp Web chatbox (#400)




  
Please try this: https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box .
  
Yes, I tried based on the wiki page. However, the problem persists.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jamestansx** [comment]
I was cleaning up my opened issues.

Currently, my workaround is to just press `tab` and the focus will change to other element. This allows the command to be usable again.

**Comment by jamestansx** [comment]
> not reproduced since v1.92.0 ?

Unfortunately, the issue still can be reproduced.
