### ISSUE TITLE
支持运行脚本的可能？

### ISSUE THREAD

**Issue by YandLiu** [gdh1995/vimium-c#401]
是否考虑加入运行脚本的功能？
cVim 可以通过在配置文件中写入脚本来用按键调用，可惜 cVim 年久失修，不太好用了
方式可参考我这 cVim 配置的最后部分：https://gist.github.com/YandLiu/8329b27b04cb4ec302c0b6da49ad319d

**Comment by gdh1995** [comment]
最近做完了”命令树“的功能，支持按命令的成功与否执行下一条命令，配合延迟命令可以执行很复杂的操作了。

很多命令其实内部有不少参数可以调，足够完成大部分函数：

按页面unmap：不支持unmap，但是可以按页面排除特定键，也能按页面/键盘焦点元素来执行不同命令。详见 https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites

`openUrl` 支持 `url` 和 `url_mask`, 比如 `map xxx openUrl url="http://webcache.googleusercontent.com/search?q=cache:$u" url_mask="$u"`，效果是自动替换 `$u` 为当前网址，然后打开拼接出的新URL。如果需要做 URL Encode，把两处 `$u` 替换成 `$s` 就行。

复制网址：`copyWindowInfo` 命令支持 `type`，`format`和`join`，`type`可以是这几种字符串：title/url/frame/tab/window/browser，来表示要复制的对象。`type`=tab/window/browser表示复制一到多个标签页的信息，此时 `format` 可以用来格式化标签页信息，默认是 `${title}: ${url}`，即标题+冒号+空格+网址；`join` 表示怎么连接各标签页，默认是换行符，可以是`"json"`表示凑成JSON格式，或者任意别的字符串直接传给join函数。

往互联网发请求：不支持。为了安全考虑本扩展不会往外界发任何请求。这也是为什么没做 Vimium 里的 ”Vomnibar 自动补全搜索词“的功能。具体到查 IP，可以给 `openUrl` 绑定一个查IP的网址，一键打开。

### 替换网址中的数字

网址数字递增：`goNext` 命令会使用”文字自动替换“这个配置项的 `n` 前缀的规则，比如配置
```
n@tid=(\d+)@tid=$${$1}@,host=bbs.wuyou.net
```
效果是：用 `/tid=(\d+)/` 捕捉整数并替换当前网址，比如 `...tid=123` 会变成 `....tid=${123}` 。然后 `goNext` 识别 `${N[/[start]:[end]:[step]]}` 的部分，找到 `123`，没找到start/end/step就用默认值0/INT_MAX/1，所以next是124，prev是122 。

`,host=bbs.wuyou.net`是用来限制作用范围的，只对无忧启动的网址生效。如果想给`goNext`配置step=2，可以写 `n@tid=(\d+)@tid=$${$1/::2}@,host=bbs.wuyou.net`。

**Comment by gdh1995** [comment]
是为了给用户一个承诺，说我这个扩展不泄露用户隐私。
嗯，具体措施是在扩展程序的这个主配置文件里面，声明了不会发js文件请求或ajax请求到任何ip



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月9日(周一) 下午5:04
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 支持运行脚本的可能？ (#401)




 
感谢写这么详细，这些很值得研究一番
 为了安全考虑不发送任何互联网请求 这个还是有点不太理解，扩展不都是用户自己配制的吗？为什么还要担心安全问题？能说下可能会有哪些方面的安全问题吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
关于网址替换，补充了完整文档： https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands

**Comment by gdh1995** [comment]
命令树在 v1.92.1 版本应该可用了，参见 https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands
