### ISSUE TITLE
Make some commands work when pages haven't loaded yet

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#411]
Like `removeTab`, `previousTab` and `nextTab`, which have nothing to do with HTML content.

**Comment by gdh1995** [comment]
You may use `chrome://extensions/shortcuts`. See https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box

**Comment by OnceThenEver** [comment]
But Chrome has limitations on browser-level shortcuts that they must begin with `Ctrl`, `Alt`, or `Cmd`, and I'd like to keep the consistency of `J` mapping `previousTab` and the likes. Are there any technical difficulties?

**Comment by gdh1995** [comment]
no, there's no method to do so in JavaScript



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 19, 2021 18:40 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Make some commands work when pages haven't loaded yet (#411)




 
But Chrome has limitations on browser-level shortcuts that they must begin with Ctrl, Alt, or Cmd, and I'd like to keep the consistency of J mapping previousTab and the likes. Are there any technical difficulties?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OnceThenEver** [comment]
I'll take it.

**Comment by OnceThenEver** [comment]
I'll take it.

**Comment by OnceThenEver** [comment]
k
