### ISSUE TITLE
Severe BUG of 1.92.2 from Chrome ! !

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#413]
Right after updating to 1.92.2, my all customary settings are erased and the advanced setting doesn't show after clicking button.
![截屏2021-08-21 22 58 31](https://user-images.githubusercontent.com/66708845/130325873-fcb4bb2a-a6ac-40b4-ab48-2616744d84ce.png)

**Comment by OnceThenEver** [comment]
https://user-images.githubusercontent.com/66708845/130326016-aa22bce4-eec8-44b0-90d8-25a28d885d3c.mov

And this

**Comment by gdh1995** [comment]
Sorry! Do your old key mappings work on normal web pages yet? Did you mean "only default key mappings can work now"?

**Comment by OnceThenEver** [comment]
Ah, it's messy, lots kind of bugs.
The most devastating bug is that it would erase settings over and over again since pasting my backup.

**Comment by gdh1995** [comment]
Sorry it's a bug when enabling syncing.

Please run in Developer Tools (press `F12` and go to `Console` panel):
``` javascript
localStorage.vimSync = "false";
chrome.storage.sync.set({ vimSync: false })
```

And then reload Vimium C.

**Comment by gdh1995** [comment]
I'll publish a new version at once. But it still need to wait for reviewing by Google.

**Comment by OnceThenEver** [comment]
Your JS code works, thank you.
By the way, the default `ge`, mapping _Vomnibar.activateEditUrlInNewTab_, didn't show in the command list, so do `gE`, but they still work.

**Comment by gdh1995** [comment]
It's an "advanced command". Please click `Show advanced commands` at the bottom right corner (scroll Help Dialog to bottom first).

![image](https://user-images.githubusercontent.com/5547703/130331379-d1dc4119-61c9-4393-a3c3-1ad290638a33.png)

**Comment by OnceThenEver** [comment]
I did.
I mean, _Vomnibar.activateEditUrlInNewTab_ was there, but there is no `ge` next to is.

**Comment by OnceThenEver** [comment]
I did.
I mean, _Vomnibar.activateEditUrlInNewTab_ was there, but there is no `ge` next to it.

**Comment by gdh1995** [comment]
Got. It's a bug of help dialog then... My name normalization lacks some branches.

**Comment by gdh1995** [comment]
Sorry to distrub you, but I find the above patch of `chrome.storage.sync.set({ vimSync: false })` is not correct. In fact it's not only useless for this bug but also imports a new bug (in the future).

Please run `chrome.storage.sync.set({ vimSync: true })` to restore its old value in synced settings.

The `false` value of `localStorage.vimSync` is just enough.

**Comment by gdh1995** [comment]
Now Vimium C v1.92.3 is waiting for reviews.

**Comment by cyberhuman** [comment]
I have the same issue with Firefox!

**Comment by gdh1995** [comment]
V1.92.3 has been published on Chrome Store.

**Comment by OnceThenEver** [comment]
Fixed, thank you!

**Comment by gdh1995** [comment]
Could you provide a snapshot of your options page?



---Original---
From: "Raman ***@***.***&gt;
Date: Tue, Aug 24, 2021 08:24 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Severe BUG of 1.92.2 from Chrome ! ! (#413)




 
I have the same issue with Firefox!
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cyberhuman** [comment]
![image](https://user-images.githubusercontent.com/979624/130703952-add874ed-9d07-434c-9b62-07535501e582.png)

![image](https://user-images.githubusercontent.com/979624/130704156-47824539-0c99-4262-aa3a-3c407751e93a.png)

I tried to import my old settings backup (from ~2 months ago), but the import does not do anything. Tried to uninstall the extension and then install it again, the import still didn't work.

**Comment by gdh1995** [comment]
Did the import button ask you to select a file?
Would you mind sending your backup file to ***@***.*** ?&nbsp; I'll test it on my computer.



---Original---
From: "Raman ***@***.***&gt;
Date: Wed, Aug 25, 2021 07:47 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Severe BUG of 1.92.2 from Chrome ! ! (#413)




 

 

 
I tried to import my old settings backup (from ~2 months ago), but the import does not do anything. Tried to uninstall the extension and then install it again, the import still didn't work.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cyberhuman** [comment]
Yes I'm presented with the dialog where I select the JSON file.

Here is the file, with private information removed:

[vimium_c-20210602_102002.txt](https://github.com/gdh1995/vimium-c/files/7043187/vimium_c-20210602_102002.txt)

**Comment by gdh1995** [comment]
@cyberhuman Hello, now v1.92.4 is available on Firefox Add-ons and Chrome Web Store. And you may take a try.

**Comment by cyberhuman** [comment]
Yes it worked with 1.92.4. Thank you!

> You are loading a settings copy:
>      * from version 1.90 of Vimium C
>      * for the Linux platform
>      * exported at 2021-06-02 10:20:02
>
> Are you sure you want to continue?
