### ISSUE TITLE
页面搜索模式能否显示目前正在高亮的是第几个？

### ISSUE THREAD

**Issue by YandLiu** [gdh1995/vimium-c#420]
类似于这样的
2/38

**Comment by gdh1995** [comment]
不太行，这个数基本上算不准，除非是特别简单的、没有输入框的页面才行。其实现在总数也不准



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月28日(周六) 晚上8:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 页面搜索模式能否显示目前正在高亮的是第几个？ (#420)




 
类似于这样的
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YandLiu** [comment]
就浏览器自带的那种计数就可以啊，浏览器自己都不准的话，用户也没理由要求扩展准吧
我的观点是有总比没有强

**Comment by gdh1995** [comment]
浏览器算得准，但扩展不行，权限不够、浏览器没给接口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月28日(周六) 晚上8:32
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 页面搜索模式能否显示目前正在高亮的是第几个？ (#420)




 
就浏览器自带的那种计数就可以啊，浏览器自己都不准的话，用户也没理由要求扩展准吧
 我的观点是有总比没有强
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
补充：对于样式简单、没有输入框的页面，“算第几个”确实是可行的，就是会引入不小的额外CPU消耗，也就是更费电、还可能卡，真有大量要搜的话建议还是走浏览器内置的吧，那个性能理论上是最好的。

Vimium C 的搜索功能主要有以下目的：
1. 配合别的命令用，比如Marks、VisualMode
2. 一定程度上增强搜索，比如有跨标签页共享的搜索历史记录、（部分）支持正则表达式、支持控制是否要求大小写匹配（Firefox自带的搜索好像已经有这个了）

但是限于浏览器提供的接口就那些、不好用，没法很好地支持：
* “统计总数”目前不包括输入框里的匹配结果
* 匹配到输入框里的文字时，无法立即滚动文字框内部到对应位置（也许能但只是我不知道）、无法控制选中文字的背景色
* 没法立即“高亮所有”——因为性能消耗较高，只有按 `Ctrl+Shift+J` / `Ctrl+Shift+K` 的时候才会去搜索所有匹配项并标记一会
* 对于样式结构复杂的页面，正则表达式模式可能不起作用、搜索漏
* 对从右往左阅读的语言可能支持得不好
