### ISSUE TITLE
How to set default status disable in Vimium C?

### ISSUE THREAD

**Issue by cirofabianbermudez** [gdh1995/vimium-c#427]
I'am using Vimium C Version 1.92.4. and I want to set the default vimium status to "disable" with the following custom key mapping:

`map Z openUrl url="vimium://status\u0020toggle-disable\u0020^\u0020Z"`

The idea is to enable the extension whenever I want, so that when my relatives use the browser it does not affect.
What am I doing wrong?
> **Extra notes:** Vimium is enabled and disabled without any problem, but I want it to be disabled by default. I tested this in Google Chrome 92.0.4515.159 and Firefox 91.0.2,  OS W10

**Comment by gdh1995** [comment]
You should use "exclusion rules" and add a line with a pattern of `^ Z`. Then all other keys except `Z` are "excluded" by default.

**Comment by cirofabianbermudez** [comment]
Thank you so much for the answer.I just tried what you suggested but it only works with specific URLs. Is there a way to set the default status of Vimium C to disable for all pages and then enable it with a key?.

**Comment by gdh1995** [comment]
you may change url pattern to match all URLs



---Original---
From: "Ciro ***@***.***&gt;
Date: Tue, Sep 7, 2021 23:09 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] How to set default status disable in Vimium C? (#427)




 
Thank you so much for the answer.I just tried what you suggested but it only works with specific URLs. Is there a way to set the default status of Vimium C to disable for all pages and then enable it with a key?.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
Like this: ![image](https://user-images.githubusercontent.com/5547703/132435591-e6439d8c-2fcc-4956-adcc-a4f4cd04dd9e.png)
