### ISSUE TITLE
Vomnibar 打开新标签页时是否支持默认后台打开？

### ISSUE THREAD

**Issue by Binly42** [gdh1995/vimium-c#429]
**What command or commands**

`Vomnibar.activateInNewTab`, etc

**How should a feature do**

功能很正常，另外确实已知可以使用 `Ctrl+Shift+Enter` （见 https://github.com/gdh1995/vimium-c/issues/163#issuecomment-618297350 

then Vimium C should do:

我的诉求是：
1. 想实现默认Enter就能后台打开，可惜我没找到合适的 param 啥的，比如试过`reuse="newBg"`就没用。
2. 另外类似 https://github.com/gdh1995/vimium-c/issues/163#issuecomment-618389472 这里提到的各种 param 的 wiki 好像也还没有？

**Browser and OS**

- Browser name:  Chrome 92.0.4515.159 (Official Build) (64-bit)
- OS name: Windows 10.0.19043 Build 19043
- Vimium C: 1.92.4

谢谢~

**Comment by gdh1995** [comment]
目前不直接支持，但是你可以这么写 `mapKey` ：
```
mapKey <enter:o> <c-s-enter>
```

**Comment by bgwwg** [comment]
打开 vomnibar 后，如果不输入，直接将焦点移到历史链接列表， `<c-enter>` 将打开新标签，如果输入搜索关键词，再向下移动焦点，`<c-enter>` 则会在本标签打开链接。请问这个行为是否正常？

**Comment by gdh1995** [comment]
正常。不输入的时候，会显示最近关闭的标签页，对它们按回车则会执行“恢复标签页”，被恢复的标签页拥有原来的前进/后退列表。这类建议条目会打上`↶`标记（在条目标题的右侧）。

**Comment by gdh1995** [comment]
呃有个问题，c-enter应当始终在新标签页打开URL，所以看起来你按ctrl后这个键的状态没生效



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月23日(周二) 晚上8:45
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] Vomnibar 打开新标签页时是否支持默认后台打开？ (#429)




 
打开 vomnibar 后，如果不输入，直接将焦点移到历史链接列表， <c-enter&gt; 将打开新标签，如果输入搜索关键词，再向下移动焦点，<c-enter&gt; 则会在本标签打开链接。请问这个行为是否正常？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Binly42** [comment]
> 呃是vimium c 问题，目前没区分`<enter>`是本来就是`Enter`，还是`mapkey`出来的，一律当成“本来就是`Enter`”了。所以去检测shift，又巧了检测到了，就强制当成`<s-enter>`处理。
> 
> 这个问题很小，回头改。

Ctrl 似乎也有类似的问题。

以下面这个配置为例：
```
map o Vomnibar.activateInNewTab preferTabs="new" searchInput
mapKey <enter:o> <a-c-s-enter>
```
1. 在Vomnibar里输入一个无空格的英文字符串`foobar`，直接按`enter`，那么往往会在后台新标签页打开`www.foobar.com`
2. 如果注释掉第二行的mapKey，那么效果则是在后台新标签页搜索`foobar`

我认为 2. 中的效果才是正常的吧，毕竟searchInput应该是默认选项才对。

---

workaround：可以在Vomnibar开头加一个`g `来指定搜索。

**Comment by gdh1995** [comment]
呃目前 `<a-c-s-enter>`这里触发了 `<a-enter>` 的逻辑，就是如果是一个单词就视为域名的主体去做补全。

是我没处理好，回头会把它们区分出来。

**Comment by gdh1995** [comment]
v1.96.3里`<a-c-s-enter>`的问题应该已经修了，请重试。
