### ISSUE TITLE
“自动切换浅色和深色模式” 下的深色模式中，对于LinkHints的自定义样式不生效

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#434]
![截屏2021-09-13 12 54 37](https://user-images.githubusercontent.com/66708845/133026302-a9084082-c7e9-473d-bd1d-0ad7ad743f34.png)

**Comment by gdh1995** [comment]
这是css写法的问题，.LH没有.D&gt;.LH优先级高，你可以用开发者工具看一下现在的样式，然后改一改选择器的写法，就能看出来哪一个更优先了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月13日(周一) 中午12:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] “自动切换浅色和深色模式” 下的深色模式中，对于LinkHints的自定义样式不生效 (#434)




 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OnceThenEver** [comment]
已从https://github.com/gdh1995/vimium-c/blob/master/front/vimium-c.css找到答案：.D>.LH
感谢！
