### ISSUE TITLE
Vimium C recognizes the hotkey to switch IME as Meta+Space and uses it

### ISSUE THREAD

**Issue by HappyCthulhu** [gdh1995/vimium-c#435]
**Describe the bug**

In search through bookmarks mode, im trying to change layout. After pressing shortcut, some bookmark paste in field

**To Reproduce**

1. Press Shift+B to open search through bookmarks window
2. Press Super+Space

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: Version 91.0.4472.114 (Official Build) (64-bit)
- Vimium C version: 1.92.4
- OS name and version: Linux, Ubuntu 20.04, i3wm

**Comment by gdh1995** [comment]
Please test `Super+Space` on https://gdh1995.cn/vimium-c/keyboard-test.html :
* open https://gdh1995.cn/vimium-c/keyboard-test.html
* click Vimium C's extension icon (at the top-right corner) and click "disable once" to make Vimium C temporarily disabled on the page
* **uncheck** the option of "Prevent all keyboard events"
* focus the input box
* then press `Super+Space` to see what it will show.

**Comment by gdh1995** [comment]
Will `Super+Space` execute pasting on an input box on common websites? Vomnibar's source code doesn't include a way to paste anything.

**Comment by HappyCthulhu** [comment]
| Event | Code | Key | Modifiers | KeyCode (legacy)
-- | -- | -- | -- | -- | --
1 | keydown | MetaLeft | Meta |   | 91
2 | keydown | Space | GroupNext | Meta | 0
3 | keyup | Space | GroupNext | Meta | 0
4 | keyup | MetaLeft | Meta | Meta | 91


I did it. Can u explain me, what does it mean? Problem is on Vimium side or this caused by another plugin?

Maybe u have any tips, how can i fix this?

**Comment by gdh1995** [comment]
If you press `o` and type `g xxx` to make Vomnibar show a suggestion of a Google search page, then will `super+space` cause Vomnibar to show `https://www.google.com/search?ie=utf-8&q=xxx` ?

**Comment by HappyCthulhu** [comment]
Yes

**Comment by HappyCthulhu** [comment]
So... Can u tell me, what does it mean?

**Comment by gdh1995** [comment]
your meta(win)+space was recognized as meta+space during Vimium C hooked it, and then Vimium C parsed the URL of a currently selected suggestion item, and then set it as Vomnibar query. This feature is to help users redo a search and modify query words or switch to another search engine.


The bug in this process is: Vimium should recognize this key as GroupNext, or at least as Meta+GroupNext, but not Meta+Space.


I'll fix it in a next version, by recongizing such keys as "<m-groupnext&gt;".



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 23, 2021 14:58 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Vimium paste text after pressing super+space while searching through bookmarks (#435)




 
So... Can u tell me, what does it mean?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
