### ISSUE TITLE
Feature Request: add `numberOfPixels` parameter to `scrollPxUp`

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#438]
Hi there. So I'd like to scroll up *slightly* faster than I scroll down.

Afaiu, this is currently not possible (`scrollUp` is too slow and `scrollPageUp` is too fast). It would be great if we could have a customizable command to scroll x pixels up/down/left/right.

Wdyt? : )

**Comment by gdh1995** [comment]
Most commands support an parameter of count, like:
map j scrollPxDown count=128


And, there's an option in Vimium C Options, named "Scroll step size", to control base step size of scrollDown/Up when count is 1.



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 16, 2021 16:58 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Feature Request: add `noOfPixels` parameters to `scrollPxUp` (#438)




 
Hi there. So I'd like to scroll up slightly faster than I scroll down.
 
Afaiu, this is currently not possible (scrollUp is too slow and scrollPageUp is too fast). It would be great if we could have a customizable command to scroll x pixels up/down/left/right.
 
Wdyt? : )
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
Or
```
# step will be 1.2  * 100 = 120 pixels
map j scrollDown dir=1.2
```

**Comment by hacker-DOM** [comment]
Thanks!
