### ISSUE TITLE
Can we have a nicer Options tab?

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#480]
The options tab looks horrible. Some text collides with each other. It is hard on eyes, and it is always blinding white. It'd be great if it followed the main theme and also looked a little better and more readable. Also for the light theme the webpage should have a light grey background rather than a blinding white.

**Comment by gdh1995** [comment]
1.

Most English / Chinese text should not collide, so maybe it's related with font families on your system.

If you find a help section shows too long, you may drag the bottom-right corner of its text box, to increase its height. Like this:

![image](https://user-images.githubusercontent.com/5547703/140536410-61e2e361-daeb-483f-844b-7efaa0a5e0f1.png)

2. 

If you use a system-level dark mode, the options page should have been in dark.

The white background color is the most popular one, at least Bing and Google search engines use it.

**Comment by zim0369** [comment]
Yes, they do use it but material colors would be much better.
And seems like the colliding font must be my font family problem. 

vimiumC's options tab does follow the system theme on the brave browser which has a dedicated option for dark theme that turns everything dark, including their own settings page and vimiumC's option page but google-chrome and chromium aren't doing so. It'd be much better if the option's page followed the vimiumC's theme. Again, material colors would be much easier on eyes. 

I know google, bing and certain other companies keep using the same css for the homepage because it's the landing page of a big company and making such changes can create problems, also people install a tonne of chrome extensions to make the search engine pages look pleasing. Maybe you should try using colors like cream #FFFDD0 and see the difference.

**Comment by gdh1995** [comment]
I won't add too many things into the inner pages, because
1. the options page won't be opened frequently
2. the blank page can be replaced easily. For example, you may write a blank `.html` file and use it as Vimium C's New Tab Page on Chrome
3. the extension package should keep small

When https://github.com/gdh1995/vimium-c/issues/287 is solved, there's a potential way to modify Vimium C options from a trusted normal web page, just like some pages hosted by `github.io`. And then the page can be filled with beautiful styles.

**Comment by zim0369** [comment]
Okay.
