### ISSUE TITLE
Disappearing search engine prefix after hitting space in vomnibar like vimium's vomnibar.

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#487]
* Steps to recreate:
  ~ Press `o` to open vomnibar
  ~ Type a search engine prefix. eg- `g`
  ~ Press `space`
  ~ The g doesn't disappear.

* Expected outcome(continued):
  ~ `g` should disappear.
  ~ Type your search.
  ~ A persistent search engine name should be displayed at the bottom of the search box.

**Comment by gdh1995** [comment]
if you type `space` for 3 times, it will auto open the query . This is a shortcut for single-hand mode.

**Comment by zim0369** [comment]
> if you type `space` for 3 times, it will auto open the query . This is a shortcut for single-hand mode.

No, you got me wrong. I want the prefix `g` to disappear. leaving behind a persistent search engine name at the bottom of the search box of vomnibar. So you're left with a clean search box with your search engine choice in place.

**Comment by gdh1995** [comment]
I don't want like the feature of hiding keywords like `g`, since I often need to modify a search engine but not query words. And it make `Vomnibar.activateUrl` very convenient when keeping a keyword showing.

**Comment by zim0369** [comment]
> I don't like the feature of hiding keywords like `g`, since I often need to modify a search engine but not query words. And it make `Vomnibar.activateUrl` very convenient when keeping a keyword showing.

IG hitting backspace before the query would work just fine to change just the search engine prefix. 

Anyways, don't you  think that modifying just the search prefix is a "niche situation"?

And Ig even if you're modifying just the search engine prefix then you're probably using your mouse or arrow keys. 

Here's how vimiums vomnibar key-presses are shorter/convenient than vimiumC's in the following search:

Search string: `g navigate through the text`

* Vimium:
 ** Keyboard:
    - ctrl+<- (4 times)
    - backspace (twice)
 ** Keyboard(alternative way)
    - ctrl+a
    - ctrl+x
    - backspace (twice)
    - ctrl+p
 ** Mouse:
    - Place the cursor at the beginning of the search
    - backspace (twice)

* VimiumC:
 ** Keyboard:
    - ctrl+<- (4 times)
    - backspace (twice)
 ** Mouse:
    - Place the cursor at the beginning of the search
    - backspace (twice)

As you can see, the number of keypresses involved in changing the search engine prefix are the same in both the cases except for an alternative way in which you can have the same result much quicker in vimium.

**Comment by zim0369** [comment]
We successfully removed the search engine prefix in both the cases with the suggested alternative way being much quicker and convenient.

**Comment by gdh1995** [comment]
When `Vomnibar.activateUrl` runs it will auto select the part of query words, and then `Shift+Home` and `Backspace` will delete the keyword part.

**Comment by gdh1995** [comment]
BTW, `Vomnibar.activateUrl` can only recognize URLs which match search engine patterns, like Google / Bing search result pages.

**Comment by zim0369** [comment]
Ummm.... Okay. As you wish.

**Comment by gdh1995** [comment]
When `Vomnibar.activateEdit` runs, it's:
![image](https://user-images.githubusercontent.com/5547703/140656612-9ee43c68-9b56-46fa-b6b5-b20bec2220d7.png)

And after `Shift+Home`, it is:
![image](https://user-images.githubusercontent.com/5547703/140656641-7c6a1a76-b761-49d3-91a7-b0b77ae3811b.png)

I've added a special feature to auto move the selection end from `g |test` to `g| test`, so that when the keyword is replaced with a key of `b`, the result is not `btest` but `b test`, and I can search directly.

**Comment by zim0369** [comment]
That's a nice one but I think most of the users would naively make edits and not use that feature. I don't know what you don't like about `C-A C-X <BS><BS> <changes> C-P`. Seems fast enough to me.

**Comment by zim0369** [comment]
And honestly, how often do you use that special feature?

**Comment by gdh1995** [comment]
in some days, very often - when I need to search in google firstly and then in google scholar or baidu scholar.


in other days, autoSearch meets most needs.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 9, 2021 01:53 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Disappearing search engine prefix after hitting space in vomnibar like vimium's vomnibar. (Issue #487)




 
And honestly, how often do you use that special feature?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
