### ISSUE TITLE
problem to set default search engine that use POST instead of Get

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#488]
Some search engine has an option that use POST request instead of GET
is there any way to send search query directly from vimiumbar?
you can disable GET form duckduckgo privacy section to test that.

**Comment by gdh1995** [comment]
Up to now it is not possible by vimium c. but you may write a html file which reads url query/hash and then sends real post messages to other websites, and then add an engine like "p: file:///path/to/forward-post.html?url=http://example.com/s&amp;query=%s"





---Original---
From: ***@***.***&gt;
Date: Mon, Nov 8, 2021 18:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] problem to set default search engine that use POSTinstead of Get (Issue #488)




 
Some search engine has an option that use POST request instead of GET
 is there any way to send search query directly from vimiumbar?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Monirzadeh** [comment]
> Up to now it is not possible by vimium c. but you may write a html file which reads url query/hash and then sends real post messages to other websites, and then add an engine like "p: file:///path/to/forward-post.html?url=http://example.com/s&amp;query=%s"
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Nov 8, 2021 18:12 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [gdh1995/vimium-c] problem to set default search engine that use POSTinstead of Get (Issue #488) Some search engine has an option that use POST request instead of GET is there any way to send search query directly from vimiumbar? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

thanks i will test this way if i getting in trouble comment here again for now i close this issue
