### ISSUE TITLE
Spidering [FEATURE REQUEST]

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#489]
It'd be convenient in some situations to make the same search across mutliple search engines at the same time. 

Frontend wise it should be easy to use just like normal prefixes:

g - google 
b - bing
m - multiple (custom list of search engines)

using the m search prefix would open multiple tabs and done : )

**Comment by gdh1995** [comment]
duplicated of #448 .



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 9, 2021 01:57 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Spidering [FEATURE REQUEST] (Issue #489)




 
It'd be convenient in some situations to make the same search across mutliple search engines at the same time.
 
Frontend wise it should be easy to use just like normal prefixes:
 
g - google
 b - bing
 m - multiple (custom list of search engines)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
