### ISSUE TITLE
自定义：dir=0.92后，翻页键往上的变成往下的了。

### ISSUE THREAD

**Issue by aronlou** [gdh1995/vimium-c#490]
map s scrollFullPageDown dir=0.92
map w scrollFullPageUp dir=0.92

按你说的，这么设置，本来想翻页可以别翻太过。
但是这样设置后，只能下翻，不能上翻了。

**Comment by gdh1995** [comment]
map&nbsp;w&nbsp;scrollFullPageUp&nbsp;dir=-0.92




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 晚上7:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 自定义：dir=0.92后，翻页键往上的变成往下的了。 (Issue #490)




 
map&nbsp;s&nbsp;scrollFullPageDown&nbsp;dir=0.92
 map&nbsp;w&nbsp;scrollFullPageUp&nbsp;dir=0.92
 
按你说的，这么设置，本来想翻页可以别翻太过。
 但是这样设置后，只能下翻，不能上翻了。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
```
map s scrollFullPageDown dir=0.92
map w scrollFullPageUp dir=-0.92
```
