### ISSUE TITLE
will lose focuse at visual mode

### ISSUE THREAD

**Issue by Banana-Two** [gdh1995/vimium-c#496]
**Describe the bug**

enter into this URL   https://zhuanlan.zhihu.com/p/64533566
enter 'v' so that we are at create mode
enter j so that  we are at the bottom of this tab
a report will show :selected has been lost
and then we can't do anything by the vimium C utill we click our mouse

**Browser, OS and Vimium C versions**

- Browser name: firefox 64 bits
- Browser version: 94.0
- Vimium C version: 1.95.0
- OS name and version: ubuntu18.04.6

**Comment by gdh1995** [comment]
If Vimium C reports `Selection has been lost`, then it's usually because a web page use JavaScript to change page content or simply remove your selection. In this situation, `VisualMode` can not know what should be selected, so it reports this error and auto exits.

When VisualMode auto exits, it will prevent keyboard events for about 1.5 seconds, so that you won't trigger unexpected commands in Vimium C's normal mode (in case that you haven't noticed the HUD).

And, when you don't press keys in 1.5 seconds, you will be allowed to press mapped keys to trigger Vimium C's commands, such as `f` for `LinkHints.activate`.

====

So, please verify whether Vimium C will work or not, when you notice the HUD tip and do nothing in following 2 seconds.

**Comment by Banana-Two** [comment]
> If Vimium C reports `Selection has been lost`, then it's usually because a web page use JavaScript to change page content or simply remove your selection. In this situation, `VisualMode` can not know what should be selected, so it reports this error and auto exits.
> 
> When VisualMode auto exits, it will prevent keyboard events for about 1.5 seconds, so that you won't trigger unexpected commands in Vimium C's normal mode (in case that you haven't noticed the HUD).
> 
> And, when you don't press keys in 1.5 seconds, you will be allowed to press mapped keys to trigger Vimium C's commands, such as `f` for `LinkHints.activate`.
> 
> ====
> 
> So, please verify whether Vimium C will work or not, when you notice the HUD tip and do nothing in following 2 seconds.

Yes,you are right. Thanks very much!
