### ISSUE TITLE
Merge with vimium?

### ISSUE THREAD

**Issue by dijonkitchen** [gdh1995/vimium-c#513]
I tried looking in both repositories, but couldn't find any discussions on combining the efforts here and in https://github.com/philc/vimium. Would all the Typescript upgrade and features be useful to everyone?

**Comment by gdh1995** [comment]
Um, this project is much aggressive, so it is not suitable tomerge back.



---Original---
From: "Jonathan (JC) ***@***.***&gt;
Date: Thu, Dec 2, 2021 08:19 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Merge with vimium? (Issue #513)




 
I tried looking in both repositories, but couldn't find any discussions on combining the efforts here and in https://github.com/philc/vimium. Would all the Typescript upgrade and features be useful to everyone?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
