### ISSUE TITLE
What's the behavior when keeping <esc> pressed?

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#523]
Given that I have `mapKey <a-m> <esc>`, if Chrome's searching matched some link's text, I can only defocus the link by pressing ⎋ for about 0.5s; ⌥m is no use. Obviously, I haven't triggered any command mapping, so the solution shall not be changing any mapping's `autoUnhover` parameter. Maybe it's not a bug because you have solved it for #325.

**Comment by gdh1995** [comment]
Sorry maybe I haven't got what you want. Do you mean the following steps?
1. make Chrome show its Find-In-Page box (maybe at the top-right corner?)
2. search for text and a link is selected
3. exit from the Find-In-Page box, and go back to the page itself
4. then, in order to blur the link:
- 1.  `<esc>` works
- 2. while `<a-m>` can not blur it

Am I right? If I am, then:
1. are you using Chrome on macOS?
2. what's the value of `Ignore keyboard layout` option on your Vimium C Options page?
3. I expect `Ignore keyboard layout` is partially checked; if not, please partially check it and then try it again.

**Comment by OnceThenEver** [comment]
Your interpretation is absolutely correct, and your solution works.
But after partially checking that, I still need to hold ⌥m or ⎋ for 0.5s to blur. What should I do to blur links with just an instant stroke?

**Comment by gdh1995** [comment]
Oh it works as designed. If a currently focused element is not editable / readonly text box, then a short `<esc>` will be ignored by Vimium C, so that pages can receive Escape events. And, a long-pressed `<esc>` will notify Vimium C to blur "any focused element" (if it exists).

**Comment by OnceThenEver** [comment]
But if I focus the link using `LinkHints.activateHover` without any parameter, instant ⌥m / ⎋ works.
Isn't it violate your intention?

**Comment by gdh1995** [comment]
It's because `LinkHints.activateHover` will setup a hook which only runs once and checks whether a next key is Esc or not.

**Comment by OnceThenEver** [comment]
Got it.
