### ISSUE TITLE
Vomnibar: How to open in the background

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c#549]
**What command or commands**
`Vomnibar.activateInNewTabInBackground`

**How should a feature do**
It would be quite handy if URLs could be opened from Vomni bar by pressing Ctrl+Enter

When a user has done such steps:

1. Open Vomnibar (`o` or `O`)
2. Type some URL, say `google.com`,
3. Now, press Shift+Enter

then Vimium C should do:

Open the entered URL in new tab in the background

**Browser and OS**

- Browser name: Chrome
- OS name: Linux

98.0.4758.80

Or is this feature already there by some other key binding?

**Comment by mizzunet** [comment]
I see that, on `o` Vomnibar, `Ctrl+Enter` to in new active tab

**Comment by zim0369** [comment]
> I see that, on `o` Vomnibar, `Ctrl+Enter` to in new active tab

Wdym by open in the background? What is background?

**Comment by gdh1995** [comment]
Yes in a default `Vomnibar.activate`, `<c-enter>` and `<s-enter>` work differently compared with those in `LinkHints`. This is because the feature are added a few years ago and at that time I was not good at designing features.

If you expect `Vomnibar` behaves just like LinkHints, then you may add `clickLike` option - like this:
```
map o Vomnibar.activate clickLike
```

And then in Vomnibar `<c-enter>` will "open a tab in background" and keep Vomnibar show.

@zim0369 `open in background` means to `open a new tab` but also `keep a current tab active` (and then the new tab is `inactive` aka `in background`).
