### ISSUE TITLE
如何使用‘智能切换到其它搜索引擎’这一命令？

### ISSUE THREAD

**Issue by Git0503** [gdh1995/vimium-c#561]
如何使用以下命令？

智能切换到其它搜索引擎（参数：keyword, reuse=current/newFg/newBg/reuse）(searchInAnother)

**Comment by gdh1995** [comment]
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年2月26日(星期六) 中午11:07
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561)





 
如何使用以下命令？
 
智能切换到其它搜索引擎（参数：keyword, reuse=current/newFg/newBg/reuse）(searchInAnother)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/155827240-828383e7-c951-475b-9d83-5e835ba30189.png)

**Comment by Git0503** [comment]
提示未能识别搜索词咋整？
——————————————————————————————————————————————————————————————————————————————









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月26日(星期六) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561)





 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
需要添加一种搜索引擎到“自定义搜索引擎”里，来识别“当前页面的网址”里的搜索词，参考 https://github.com/gdh1995/vimium-c/wiki/Search-engine-rules#parsing-regexp-pattern

**Comment by Git0503** [comment]
oh，天哪，只能识别“当前页面的网址”里的搜索词，我还以为在任意页面选中就能直接用映射好的搜索引擎搜索




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月26日(星期六) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561)





 
需要添加一种搜索引擎到“自定义搜索引擎”里，来，参考 https://github.com/gdh1995/vimium-c/wiki/Search-engine-rules#parsing-regexp-pattern
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
选中搜索不是这个，是autoOpen keyword=xxxx



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月26日(周六) 晚上7:12
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561)




 oh，天哪，只能识别“当前页面的网址”里的搜索词，我还以为在任意页面选中就能直接用映射好的搜索引擎搜索 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年2月26日(星期六) 中午11:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561) 
 
 
 
 
 
   
 需要添加一种搜索引擎到“自定义搜索引擎”里，来，参考 https://github.com/gdh1995/vimium-c/wiki/Search-engine-rules#parsing-regexp-pattern 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Git0503** [comment]
哇，太棒了，这就是我想要的功能






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月26日(星期六) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561)





 选中搜索不是这个，是autoOpen keyword=xxxx 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年2月26日(周六) 晚上7:12 
 收件人: ***@***.***&amp;gt;; 
 抄送: "Dahan ***@***.******@***.***&amp;gt;; 
 主题: Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561) 
 
 
 
 
  oh，天哪，只能识别“当前页面的网址”里的搜索词，我还以为在任意页面选中就能直接用映射好的搜索引擎搜索  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年2月26日(星期六) 中午11:51  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [gdh1995/vimium-c] 如何使用‘智能切换到其它搜索引擎’这一命令？ (Issue #561)  
   
   
   
   
   
     
  需要添加一种搜索引擎到“自定义搜索引擎”里，来，参考 https://github.com/gdh1995/vimium-c/wiki/Search-engine-rules#parsing-regexp-pattern  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.   
  You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
