### ISSUE TITLE
Unable to expand/shrink multi-level menu

### ISSUE THREAD

**Issue by gh-orange** [gdh1995/vimium-c#566]
**Describe the bug**

Unable to expand/shrink antd 3.x multi-level menu using Vimium C

**To Reproduce**

1. Go to URL "[antd 3x collapsed inline menu](https://3x.ant.design/components/menu/#ccomponents-menu-demo-inline-collapsed)"
2. Click the blue square button to shrink menu list
3. Click the blue square button again to expand menu list
4. Press key `f` to simulate a click on multi-level menu "Navigation One"
5. Expected to expand/shrink it, but nothing happened 

**Browser, OS and Vimium C versions**

- Browser name: MS Edge
- Browser version: 98.0.1108.62 (x64)
- Vimium C version: 1.96.6
- OS name and version: Windows 11 Version 21H2 (Build 22000.493)

**Comment by gh-orange** [comment]
I found that the `transitionend` Event is missing from the *simulated operation* compared to the *actual operation*

**Comment by gdh1995** [comment]
The page has multiple "Navigation One" menu items, so which one did you mean? Please give some detailed snapshots if possible.


During my tests on Edge (Chromium) 98 x64 on Win 10, Vimium C can toggle the first "dark" "Navigation One" with Option 5-8 .


The `transitionend` means the end of an animation task, so usually it is not the root cause.




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Mar 5, 2022 11:50 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;Re: [gdh1995/vimium-c] Unable to expand/shrink multi-level menu (Issue #566)





 
I found that the transitionend Event is missing from the simulated operation compared to the actual operation
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gh-orange** [comment]
Sorry I write a wrong URL, it should be [components-menu-demo-inline-collapsed](https://3x.ant.design/components/menu/#components-menu-demo-inline-collapsed)
1. Click the blue square button to shrink menu list
2. Click the blue square button again to expand menu list
3. Press key `f` to simulate a click on multi-level menu "Navigation One"
4. Expected to expand/shrink it, but nothing happened

**Comment by gh-orange** [comment]
![GIF 2022-3-5 12-56-18](https://user-images.githubusercontent.com/18071349/156868684-acf09f3c-ddaf-4c40-b7d6-48fb7fb00f84.gif)

**Comment by gdh1995** [comment]
confirmed




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月5日(星期六) 中午1:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gdh1995/vimium-c] Unable to expand/shrink multi-level menu (Issue #566)





 

 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
