### ISSUE TITLE
Suggestion for less dense link navigation (`f`)

### ISSUE THREAD

**Issue by indigoviolet** [gdh1995/vimium-c#575]
**What command or commands**

New feature suggestion

**How should a feature do**

On many websites, the `f` feature (link-hinting) ends up being very dense. example:

![image](https://user-images.githubusercontent.com/114010/158890004-2c1a4a2e-f2d8-4ed7-a6d9-8b69ffe4b4ec.png)

1. One idea for how to improve this could be:

Instead of hinting every link, consider a mode which hints only a subset of links (ideally distributed evenly on the page, though exactly how to figure this out from the DOM is unclear to me at the moment). Then, allow cursor keys to move to nearby links (similar to https://chrome.google.com/webstore/detail/caret-browsing/fklpgenihifpccgiifchnihilipmbffg?hl=en). 

This combination allows the user to jump to a different region of the page using the hints, and then "locally" navigate with the cursor. 

2. Another idea which perhaps is easier to implement but less general: allow users to define per-site filters (regular expressions) that define the subset of the links that are hinted.

**Comment by gdh1995** [comment]
The 2nd idea has been implemented by some options of `LinkHints` and the command named `runKey`, Please try https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints .

As for the 1st idea, I think it's too complex to make users understand "what are hinted", because Vimium C can not ensure all clickable elements will be found, then with this idea applied, a non-hinted element may be hinted after a key, or never hinted by Vimium C. So I won't implement it.
