### ISSUE TITLE
hypothes.is 等网页高亮工具的快捷键在光标和自由选择模式下被屏蔽/占用

### ISSUE THREAD

**Issue by sky31even** [gdh1995/vimium-c#586]
### 背景

[hypothes.is](https://web.hypothes.is/)是一个网页高亮和标注工具，选中一段文字然后按 a 或者 h（或者点击悬浮窗按钮），就可以批注或者高亮。

如图：
<img width="616" alt="image" src="https://user-images.githubusercontent.com/49628447/160045336-cb47ee42-566b-4351-9aac-43ecea4ef5f3.png">

### 问题

使用 vimium c 的文本选择模式选择好文本之后，按 a 或者 h 都没反应，因为 h 被占用（向左滚动），a 以及所有其他扩展的快捷键应该是在这种状态下都是被屏蔽了。

### 建议

1. 允许自定义文本选择模式的操作快捷键，比如将 j\k\h\l 移到其他位置；
2. 允许取消一部分文本选择模式下对其他浏览器扩展的快捷键的屏蔽，比如这个案例里面的 a 和 h。

**Comment by gdh1995** [comment]
You may use https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#pre-mode-mapkey like:
```
# fake1 means to do nothing, so it won't be blocked by Vimium C
mapKey <j:v> <fake1>
mapKey <a:v> <fake1>
# use F1 to move caret down
mapKey <f1:v> j
```

Or use `passNextKey` to bypass some next keys:
```
# press F1, and then a next (composed) key will be ignored by Vimium C
# f1~f12 will be passed by VisualMode of Vimium C, so their mappings still work
map <s-f1> passNextKey
```

**Comment by sky31even** [comment]
passNextKey really helps !! thanks ~

btw is therer any possible solution to make a consecutive combo with only 1 action:

sample:  press <s-f1> then send 2 action consecutively.... like "1.paasNextKey 2. h" ~~

**Comment by gdh1995** [comment]
To run more than 1 commands of Vimium C, use `runKey` - https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands .

To simulate a key like `h`, use `dispatchEvent`:
```
# simulate a key event of "h"
run <v-fake_h> dispatchEvent#key=h%2C72%2CKeyH
# simulate both keydown and keyup of h
run <s-f1> (fake_h)+-fake_h
```

Note that `passNextKey` should not be used before `dispatchEvent`, because:
1. it always waits for exiting PassNextMode before running a next command
2. events from `dispatchEvent` are always auto-ignored by Vimium C

Currently you can not run a Vimium C command using keys except `F1~F12`, or you have to create a `mapKey` rule in normal node, so I'll update logic and a next version of Vimium C will support:
```
mapKey <h:v> <v-fake_2h>
run <v-fake_h> dispatchEvent#key=h%2C72%2CKeyH
run <v-fake_2h> fake_h+-fake_h
```

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try. It supports `map <***:v> <v-***>` now.
