### ISSUE TITLE
Alt+B/F/D to move caret in vomnibar does not work under Firefox

### ISSUE THREAD

**Issue by leodream** [gdh1995/vimium-c#597]
**Describe the bug**

The following Bash-like shortcuts do not work in Firefox

- Alt+B move caret a word forward
- Alt+F move caret a  word backward
- Alt+D delete a word

On the other hand, the following do work
- Ctrl+J/K to go to a next/previous suggestion item
- Shift+ArrowDown/ArrorUp to pageDown / pageUp.
- Alt+NUM to select n-th item

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 98.02
- Vimium C version: 1.97.0
- OS name and version: Linux 5.17.1, Windows 10

**Comment by gdh1995** [comment]
Have you enabled `privacy.resistFingerprinting` on `about:config`?

**Comment by leodream** [comment]
Just tried it.
If i set `resistFingerprinting` to `true`, the behavior of these shortcuts change.

- alt-F -> activate the "File" menu
- alt-B -> activate the "Bookmarks" menu
- alt-D -> focus the address bar

If the setting is `false`, the default, all these shortcuts do nothing.

**Comment by gdh1995** [comment]
Oh it's a limit of Firefox - Firefox doesn't provide a way to move caret in an input box easily, while it's too complex and somehow hard to simulate it using JS code.

**Comment by leodream** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1527627 ?

That's a pity. It is a very nice feature and must make those who do shell stuff a lot feel at home. I was surprised to learn that vimium-c also supports such shortcuts in https://github.com/gdh1995/vimium-c/issues/499 (it always does). Strange that it is not mentioned in the wiki.

**Comment by gdh1995** [comment]
I know the related API.  But the real problem is not how to set a selection range, but how to find the new position after "moving right by a word". Although in English text can be split by spaces, but text in some other languages (like Chinese) can not.

Maybe I should make moving caret to another space as a fallback on Firefox...

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try. I added simulated selection editing on the version for Firefox.

**Comment by leodream** [comment]
- Alt+F is working
- Alt+D behaves like Alt+F and does not delete words
- Alt+B will move the caret behind the first char
![test](https://user-images.githubusercontent.com/2774809/165467863-05233e1c-e5b6-4059-9d47-6b97ba525bf1.gif)

Vimium-c 1.98.0
Firefox 99.0.1

**Comment by gdh1995** [comment]
Confirmed.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.2 for Firefox has been published, and you may take a try.

**Comment by leodream** [comment]
work as expected now.

**Comment by gdh1995** [comment]
I know the related API.&nbsp; But the real problem is not how to set a selection range, but how to find the new position after "moving right by a word". Although in English text can be split by spaces, but text in some other languages (like Chinese) can not.


Maybe I should make moving caret to another space as a fallback on Firefox...



---Original---
From: "Leo ***@***.***&gt;
Date: Sat, Apr 2, 2022 16:12 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Alt+B/F/D to move caret in vomnibar does not work under Firefox (Issue #597)




 
https://bugzilla.mozilla.org/show_bug.cgi?id=1527627 ?
 
That's a pity. It is a very nice feature and must make those who do shell stuff a lot feel at home. I was surprised to learn that vimium-c also supports such shortcuts in #499 (it always does). Strange that it is not mentioned in the wiki.
