### ISSUE TITLE
currentWindow option for resotreTab

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#611]
Like that for `Vomnibar.activateTabs`

**Comment by gdh1995** [comment]
accepted.

**Comment by gdh1995** [comment]
This feature has been added in code and will be available in a next release.

However, unfortuantely it only works on Firefox, because Chrome doesn't tell extensions which window a closed tab was in.

**Comment by OnceThenEver** [comment]
What about recording the numbers of every window's tabs, and binding the closed tab's URL with the window that had the tab number decremented?

**Comment by gdh1995** [comment]
This idea is not so reliable because there can be lots of tab / window operations before restoring an old tab.

And, Vimium C won't record extra info for closed tabs - the best way to respect user privacy is not to access it.

**Comment by OnceThenEver** [comment]
Can we submit feedback to Chromium suggesting providing the API to access the information? Or do you think they don't provide it to respect privacy as well?

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.2 for Firefox has been published, and you may take a try.

**Comment by gdh1995** [comment]
As far as I guess, the team hates feature changes, since changes mean more work.



---Original---
From: ***@***.***&gt;
Date: Thu, May 5, 2022 19:36 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] currentWindow option for resotreTab (Issue #611)




 
Can we submit feedback to Chromium suggesting providing the API to access the information? Or do you think they don't provide it to respect privacy as well?
