### ISSUE TITLE
Can i copy an image by hitting? 

### ISSUE THREAD

**Issue by alps2006** [gdh1995/vimium-c#612]
Thanks for your job, this is a great tools in browser.  
I want to copy an image (not image link)  quickly,  but i can't see any related command.

I guess that this is a new feature,  can you implement it ?

**Comment by gdh1995** [comment]
Accepted.

**Comment by gdh1995** [comment]
Hello, with v1.98.3 you may write key mappings like this to select and copy image:
```
# please replace "xxx" with a key sequence you like
map xxx LinkHints.activateCopyLinkText match="img,svg" richText
```

Note this can only copy things as "HTML section", so it can be recognized by softwares like MS Office Word, but those software who want exactly images may not support it.

I have a plan to add a new LinkHints mode to copy images as "Image file" directly, in a future version of Vimium C.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.99.0 now supports `LinkHints.activateCopyImage`, and it has been available on Firefox Add-Ons and Chrome Web Store, so you may take a try.

The command will copy image into a PNG file in your system clipboard, instead of an HTML section, so that images can be pasted onto most softwares.

**Comment by alps2006** [comment]
Thanks for your supporting,  it works for me  perfectly.
