### ISSUE TITLE
Yanking and pasting shortcuts

### ISSUE THREAD

**Issue by ahmedeidand** [gdh1995/vimium-c#621]
Is there any way to remap default yank and paste keys in Vomnibar mode ?

**Comment by gdh1995** [comment]
What do you mean by `yank and paste` in Vomnibar?

**Comment by gdh1995** [comment]
If you want to map other keys to work as `Ctrl+C/V` on Vomnibar, then currently there's no way to do so.

I'll allow `editText` to run on Vomnibar in a next version of Vimium C, so you may add arbitrary editing actions you want.

**Comment by ahmedeidand** [comment]
Thank you so much 👏👏

**Comment by gdh1995** [comment]
Now in Vimium C v1.99.0, Vomnibar use `Ctrl+C` to copy a suggestion's URL, and `Ctrl+Shift+C` to copy `title: URL`, if only there's no text selected.

I've given up the idea to add a full-featured `editText` on Vomnibar, because it seems not powerful enough, and most of its current usages on Vomnibar can be implemented by `mapKey`.
