### ISSUE TITLE
Icon color for "Vimium C is not running on this page"

### ISSUE THREAD

**Issue by palandovalex** [gdh1995/vimium-c#629]
When a user will open special browser pages, as browser://*, view-source:*,  in firefox also https://addons.mozilla.org/* and etc.

then Vimium C should do:

Make "vimium c"  icon color - gray.

**Comment by palandovalex** [comment]
how it looks now:

![vimium_c_icon](https://user-images.githubusercontent.com/75374436/168145821-eb5a8268-2c1a-442a-ac2f-6d6d6c1b510b.png)

how it shouls looks:

![vimium_c_icon_correct](https://user-images.githubusercontent.com/75374436/168145860-2beeee37-267b-4be8-bb5b-6429f8c2f7ae.png)

**Comment by gdh1995** [comment]
It's on purpose and in order to reduce CPU cost.

To show the disabled icon on non-accessible pages, Vimium C will have to listen on `browser.tabs.update`, but this API is not well-designed (as far as i understand), because it can be triggered very frequently, by many types of changes including a new title / url hash.

**Comment by palandovalex** [comment]
can it be realised by 
try{
  test action with activeTab
}
except(TabProtectedException){
 change icon to gray
}

**Comment by gdh1995** [comment]
No. Although it's easy to set a different icon, the problem is:
* to reduce CPU cost, the default icon is orange
* when a tab is created, it may be accessible (running Vimium C) or inaccessible
* but the status can not be determined until a tab finishes loading
  * Vimium C can run on some extensions and even `chrome://*` pages
* so, there're 2 ways to set icons:
* 1. set the icon gray on tab creating, and set it orange when a tab is ready and reports it's running Vimium C
* 2. or: wait for hundreds of milliseconds, and then set icon gray if no running signals
* but, the 1st way causes much flicker; the 2nd way causes lots of timers (which costs CPU) and still some ficker

Besides, when a page ends (is replaced), Vimium C also has to guess whether the new page is accessible or not, which requires more timers and heavier flicker.

What's worse is, if another extension creates an inaccessible `<iframe>` in an accessible page, it's very complicated to track the iframe's URL change, too.

Therefore, the fastest way is just not to change icon on an inaccessible page (tab or iframe) - since in most situations such pages are very easy to recognize.
