### ISSUE TITLE
Make g-f account for app-drawer and nav tags

### ISSUE THREAD

**Issue by sluongng** [gdh1995/vimium-c#63]
Currently <g-f> and <g-F> are not very useful except when use on site that use iframe

However, popular sites such as Youtube use app-drawer tab to show their sidebar instead:

- Youtube: <app-drawer/> left side bar
- Github + Octotree browser extension: <nav/>
- Twitch.tv: <div class="side-nav"/> for side bar, <main/> for main

This make scrolling with Vimium / Vimium-C quite difficult and bad experience for user.

Proposal: <g-f> and <g-F> should consider side-bar elements and rotate focus around them for better scrolling.

Thanks.

**Comment by gdh1995** [comment]
`gf` is designed to switch among frames, because it is impossible (for pages extensions like Vimium) to correctly tell from side-bar/dialog/... elements on all various websites.

Then `LinkHints` may help you, because if there's any scrollable box / iframe element, Vimium C shows a dark red hint for it.

BTW, I tried Octotree and it's hard to activate its tree without a real mouse, so unless its developers expose some "public" and "stable" interfaces to show/hide the trees, it's also impossible for Vimium C to click and show it.

**Comment by sluongng** [comment]
My concern is not really about clicking the links in these region. Its more about wanting to scroll / navigate regions inside the DOM that are scrollable but has not been `clicked` on yet.

Currently if i have an expanded tree in Octotree, the only way to scroll it with this extension is to attempt clicking on a folder first (thus put the *focus* onto that element), then `j k` could be used to scroll inside the tree.

If <g-f> was not a good idea, perhaps we need a feature to `fake click` and element on the screen to change focus and easier scrolling?

**Comment by gdh1995** [comment]
Please try `LinkHints.activateModeToHover`. This can simulate mouse hover events and even trigger class names on one special element.

An advanced usage of this command is:
```
map Ff LinkHints.activateModeToHover \
  toggle={".bilibili-player-area":"video-control-show"}
```

**Comment by gdh1995** [comment]
Does it (`LinkHints.activateModeToHover`) work?

**Comment by sluongng** [comment]
`LinkHints.activateModeToHover` worked with exception for some niche cases.

Closing issue.

**Comment by gdh1995** [comment]
So what's the exception cases?Maybe I can fix them, too.
