### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by exostin** [gdh1995/vimium-c#633]
Hello, I mostly completed a Polish translation for vimium-c, but I have a question: what exactly does "no pass keys" mean?

**Comment by gdh1995** [comment]
Thank you.

`No pass keys` is an error message when the command `passNextKey` finds there're currently no `mapKey` rules.

By default, `passNextKey` will make Vimium C ignore any `mapKey` rule during handling a next (composed) key. For example, if there's `mapKey <a-e> <esc>`, then after triggering `passNextKey`, `Alt+E` won't make Vimium C "exit anything".

**Comment by gdh1995** [comment]
`No pass keys` is an error message when the command `passNextKey` with a parameter of `normal` finds there're currently no `mapKey` rules.

`passNextKey` has two basic modes. If its `normal` parameter doesn't exist or is `false`, then Vimium C will pass a next key (or N keys if `command count > 1`) to web pages, instead of blocking and handling the key.

If `normal` is `true` (like `map xxx passNextKey normal`), then Vimium C will ignore exclusion rules when handling a next key.
For example, if there's a matched exclusion rule on a current page, and the rule's "pass key" is "f", then by default `f` will be sent to the page, whether there's a key mapping of `f` or not; while after `xxx`, a following `f` will trigger configured command like `LinkHints`.
