### ISSUE TITLE
no favicons in Firefox

### ISSUE THREAD

**Issue by balta2ar** [gdh1995/vimium-c#65]
Hi! I'm using version `Vimium C 1.76.5` and I noticed that there are no favicons in Vomnibar (`T` shortcut). However, favicons are displayed in Chromium. Is this a known limitation or a bug? Thanks.

**Comment by gdh1995** [comment]
Can not support it on Firefox, because Firefox has not provided such a feature to web extensions.

In fact, for such types of extensions, Firefox has more limitations than advantages, compared with Chrome.

**Comment by balta2ar** [comment]
OK, got it, thanks for the response. I guess, this is the related bug request on Mozilla bugtracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1411120. I don't think it's gonna be fixed any time soon, so I'm closing this (though feel free to reopen).

**Comment by gdh1995** [comment]
Well, in fact history items also don't expose their icons, and https://bugzilla.mozilla.org/show_bug.cgi?id=1315616 is more like what Vimium C does on Chrome - Chrome allows URLs like `chrome://favicon/https://any-domain/any-path`.

But it seems that Firefox team think the kinds of URL expose too many information to extensions, and they have even blocked URLs like `https://plus.google.com/_/favicon?domain_url=http://domain/path` by default, to "avoid tracking user actions"...

There've been 2~3 years since the issue was filed, and maybe 3 more years are needed.

BTW, Vomnibar's "tab" mode supports favIcons on Firefox, in an ugly and costly way.
