### ISSUE TITLE
How to simulate the ArrowLeft and ArrowRight when in insert mode

### ISSUE THREAD

**Issue by Generalost** [gdh1995/vimium-c#677]
I have tried the following config with https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands as reference, replaced the key and keycode. But it just don't work.
```
map <v-de> dispatchEvent
env s element="select"
env t element="textarea"
run <c-h:i> #key=ArrowLeft%2C37+de+-de,#key=ArrowRight%2C39+de+-de
run <c-l:i> -<c-h:i>
```
How should I set the correct configuration for this feature?

And I don't get the meaning of `+de+-de`, it seems this [doc](https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands) does not contain the explanation for the statement. ( I know it's something related to dispatchEvent but still don't get it)

**Comment by gdh1995** [comment]
These 2 command do simulate ArrowLeft and ArrowRight, but I'm afraid they're not you really want.

`dispatchEvent` can only simulate "events" in JavaScript-code level, while it can not make your browser execute default actions on such events, unless a web page has written some code to do something on (simulated) events.

If you want to move caret, you may need the command named `editText`:
```
map <c-h:i> editText run="auto,backward,character"
map <c-l:i> editText run="auto,forward,character"
# in your rule, `env s` and `env t` are not used, so here they're removed
```

====

1. `+de+-de` means to run `de` with a default `count=1` and then `de` with `count=-1`.
2. `de` is a short name of `<v-de>`, if only there's no mapping rule like `map <de> xxxxxx`

====

BTW, sorry there's a bug of `dispatchEvent key="..."` since v1.97.0, that it won't setup `KeyboardEvent.code` unless `key` has two commas, like `#key=ArrowLeft%2C37%2C` .

**Comment by Generalost** [comment]
> These 2 command do simulate ArrowLeft and ArrowRight, but I'm afraid they're not you really want.
> 
> `dispatchEvent` can only simulate "events" in JavaScript-code level, while it can not make your browser execute default actions on such events, unless a web page has written some code to do something on (simulated) events.
> 
> If you want to move caret, you may need the command named `editText`:
> 
> ```
> map <c-h:i> editText run="auto,backward,character"
> map <c-l:i> editText run="auto,forward,character"
> # in your rule, `env s` and `env t` are not used, so here they're removed
> ```
> 
> ====
> 
> 1. `+de+-de` means to run `de` with a default `count=1` and then `de` with `count=-1`.
> 2. `de` is a short name of `<v-de>`, if only there's no mapping rule like `map <de> xxxxxx`
> 
> ====
> 
> BTW, sorry there's a bug of `dispatchEvent key="..."` since v1.97.0, that it won't setup `KeyboardEvent.code` unless `key` has two commas, like `#key=ArrowLeft%2C37%2C` .

> 

It worked. Thanks for your explanation!
