### ISSUE TITLE
Hard to understand new features such as "Substitute URLs and text during commands"

### ISSUE THREAD

**Issue by av930** [gdh1995/vimium-c#678]
**How should a feature do**

When a user has done such steps:

then Vimium C should do:
If I currently on site : http://mydomain.com, it is expected to open "http://mydomain.com/computer" ? isn't it?
Please add more simple example such as "how to open url by string abbreviation"

**Browser and OS**

- Browser name: 
- OS name: Chrome in Windows 10

**Comment by gdh1995** [comment]
If you just want "abbr", you may add a new "search engine":
```
bing: https://www.bing.com Bing
```

And then `bing` on Vomnibar will mean Bing.com.

The feature to `substitute URLs and text` provides a way to modify any text and replace or extract its part, so that it will support such usages:
* replace a URL of a mobile webpage with its PC version (e.g. `item.m.jd.com/product/***` vs. `item.jd.com/***`)
  * then `openCopiedUrlInNewTab` will be much more powerful
  * can also replace a SSH git address with its HTTP version (`git@github.com:gdh1995/vimium-c.git` vs. `https://github.com/gdh1995/vimium-c`)
  * or normalize several domains and IPs into a standard domain name
* modify suffixes of URLs made by the command `goUp` (`gdh1995/vimium-c/pull/` to `gdh1995/vimium-c/pulls`)
* extract a real target URL from encoding URLs (`www.google.com/url?url=www.bing.com` vs. `www.bing.com`)
* and even specify how to make a next/previous URL during the command `goNext`

See https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands
