### ISSUE TITLE
Feature request - Caps Lock feedback

### ISSUE THREAD

**Issue by ygormagalhaes** [gdh1995/vimium-c#68]
Hello everyone! I've been thinking of a feature that can improve the user experience. The functionality is to give some feedback on whether caps lock is on or off in the toolbar icon or anything visual, in order to avoid unexpected behavior with case sensitive key shortcuts.

What do you think?

**Comment by gdh1995** [comment]
On v1.76.6, there's 2 ways to work it around:

1. There's an advanced option "Ignore CapsLock status" to make Vimium always ignore CapsLock.

2. You may write `map FF showTip text="Maybe\u0020Caps\u0020Lock\u0020is\u0020ON\u0020!!!"`, and then <kbd>FF</kbd> (two UPPER-CASE `F`) will show a tip at the bottom-right corner.
  - I use this, because I use `f` to show LinkHints, and I often retry to press <kbd>f</kbd> if no hints.
