### ISSUE TITLE
List all search engines with a command like Vomnibar.activateSearchEngines

### ISSUE THREAD

**Issue by Fred-Vatin** [gdh1995/vimium-c#694]
`Vomnibar.activateTabs` or `Vomnibar.activateHistory` list tabs and history. It would be nice to have a command to list search engines with their keywords. It could be named as `Vomnibar.activateSearchEngines`.

**Comment by gdh1995** [comment]
Why do you want this? All available engines are defined on Vimum C Options page:

![image](https://user-images.githubusercontent.com/5547703/183543406-1e4c507f-5ab4-4c99-a8cb-9abec55623d9.png)

**Comment by freMea** [comment]
Because I have a lot of search engine and can’t always remember their keywords or their domain to call them.

**Comment by gdh1995** [comment]
I suggest that you may click `Auto Resize` button and the read you list of search engines:
![image](https://user-images.githubusercontent.com/5547703/183658168-99b9d0ac-e24c-4c66-9ae3-215a55e4c4fc.png)

Whenever you have used a search engine for several times, you will be able to remember its name easily and quickly. And for those seldom used, you can assign longer but representative names (like website domains' main names), so that if you know a site, you'll know its name.

**Comment by freMea** [comment]
It’s more of a workaround but ok.

**Comment by gdh1995** [comment]
Um, up to now I'm not interested in this. You may keep this issue open to let other users vote it.
