### ISSUE TITLE
Slow loading on sourcegraph pages with big files

### ISSUE THREAD

**Issue by sluongng** [gdh1995/vimium-c#751]
**Describe the bug**

File load very slowly with vimium-c enable vs without.

**To Reproduce**

1. Go to https://sourcegraph.com/github.com/bazelbuild/remote-apis@aa29b91f336b9be2c5370297210b67a6654c0b72/-/blob/build/bazel/remote/execution/v2/remote_execution.pb.go?L55
2. Try to scroll on the file with / without Vimium-C enabled.

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: Version 106.0.5249.103 (Official Build) (x86_64)
- Vimium C version: 1.99.3
- OS name and version: MacOS latest

```
Google Chrome | 106.0.5249.103 (Official Build) (x86_64)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | macOS Version 12.6 (Build 21G115)
```

Here is a profiling of the page
![image](https://user-images.githubusercontent.com/26684313/195557862-b39abc7e-a825-4bfc-9b76-cdc48caf6028.png)

and tracing into the "Timer Fired" stacks showed that it's from Vimium-C minified JS. Disabling Vimium-C and the issue is gone.

**Comment by gdh1995** [comment]
Confirmed and it can be worked around.

**Comment by gdh1995** [comment]
If you accept a zip package to test, you may try this: [vimium-c-1.99.3-dev-chrome.zip](https://github.com/gdh1995/vimium-c/files/9775814/vimium-c-1.99.3-dev-chrome.zip), though the way the version works around this issue is not perfect.

It's because `[].indexOf.call(HTMLCollection, Element)` in `content/extend_click.ts:386` runs too slow, and the page injects much more click listeners than it needs.

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try.
