### ISSUE TITLE
Edit keybindings / search engines in a text editor

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#767]
Another random question:

I have pretty large `keybindings` and `search engines` sections. (I use the blank feature of search engines as a bookmarking engine)

Is there any way to edit this in a text editor, other than copy+paste? I looked in my Vivaldi directory and I coudn't grep for lines in that file*, but I could be wrong.

* I'm concluding it's stored in some db?

**Comment by hacker-DOM** [comment]
I think I got it to work (at least for browsing) with [python leveldb](https://pypi.org/project/leveldb/) but it did require me to close Vivaldi (lock)

1. cd "/Users/dteiml/Library/Application Support/Vivaldi/Default/Local Extension Settings/hfjbmagddngcpeloejdejnfgbamkjaeg"
2. mkvirtualenv vimium
3. pip install leveldb ipython
4. ipython
5. import leveldb
6. db=leveldb.LevelDB(".")
7. [x[0] for x in db.RangeIter()]
8. db.Get(b'searchEngines')

@gdh1995 Is there anything VimiumC can do to allow this feature? 😍

**Comment by gdh1995** [comment]
Yes it's usually a leveldb file. Vimium C stores its configuration using standard browser-provided APIs which are designed for extensions, and Chrome and Firefox save this data into DB files (one file for every extension's configuration).

But this is not recommended, because it's unsafe, and your browser may change how it saves extension data in any time.

You may copy-modify-paste-back, or export configuration into a JSON file, modify it and then import the file. With the later trick, you just need to take care of JSON-encoding by yourself; and you may trace your changes using tools like Git.
