### ISSUE TITLE
[PDF Viewer] Vimium-C shortcuts do not work unless I first click on the PDF file

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#776]
**Describe the bug**

When I open a PDF file in Brave, I cannot use <kbd>j</kbd>, <kbd>k</kbd>, or other shortcuts to navigate the file. I must first click somewhere on the page before using the shortcuts.

**Browser, OS, and Vimium C versions**

- Browser name: Brave
- Browser version: 1.45.116 Chromium: 107.0.5304.91
- PDF Viewer for Vimium C version: 2.15.349
- OS name and version: macOS 13.0

This issue is not specific to this version of Brave or macOS. I have experienced this issue since I first started using PDF Viewer for Vimium-C.

**Comment by gdh1995** [comment]
I guess it's because the PDF iframe couldn't grab focus, so you may try: **enable and then disable** `Prefer keeping URLs in the address bar unchanged` on PDF Viewer's options panel:

![image](https://user-images.githubusercontent.com/5547703/202599729-5d8482c1-593b-4e10-b800-a8317cd1ed12.png)

This action is to work around a bug of `PDF Viewer for Vimium C`:
- its default state of `Prefer keeping URLs ...` is different from the one `enabled and then disabled`
