### ISSUE TITLE
Feature Request meta: Make Github sponsor account

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#786]
So I recently sponsored `kovidgoyal` on Github and I really liked the experience (and I got a badge on my profile haha). I checked outOpenCollective, but it doesn't seem to support monthly sponsortship. Paypal is an option, but I'd like to keep all my sponsorships in a reviewable place, e.g. Github :-)

**Comment by gdh1995** [comment]
Thank you very much. But I'm living in China (mainland), while GitHub Sponsors (beta) doesn't support my region, so it put my account in a "wait list" (https://github.com/sponsors/gdh1995/waitlist):

![image](https://user-images.githubusercontent.com/5547703/200184564-a7a58271-f805-4ec2-a5c9-35fb412d7cfd.png)

I once made a list of some sponsors from PayPal and OpenCollective records, although I haven't updated it since 2021-02.
