### ISSUE TITLE
[Feature Request] Define format of `yy` shortcut on options page

### ISSUE THREAD

**Issue by n4n0GH** [gdh1995/vimium-c#80]
**Describe the feature you'd like to see**
When using `yy` to yank the tab info, Vimium-C currently pulls the data in form of `Tab Title: URL` with no option to only grab the URL.
A neat feature would be to have the possibility to define your own formatting for the command on the options page or enable users to create more shortcuts with additional formatting commands.

**Additional context**
Vimium's default behaviour is afaik to just yank the current tab's URL.

**Comment by n4n0GH** [comment]
Very sorry, this is already possible by using `map yy copyCurrentUrl type="url"` for example to grab only the URL. My bad.

**Comment by gdh1995** [comment]
Sorry, this is a regression of Vimium C v1.78.0. `copyCurrentUrl` should copy not `title: url` but url itself, while `copyWindowInfo` is used to copy all info (with a default format of `title: url`). so I'll fix it in a next released version.

The `type="url"` does work, and in fact the only difference among `copyCurrentTitle`, `copyWindowInfo` and `copyCurrentUrl` is that their `type`s are different. This bug is because of a wrong default value of `type`.

**Comment by gdh1995** [comment]
Vimum C v1.78.2 has been released on Firefox Add-ons, so you may take a try. Thanks!

**Comment by n4n0GH** [comment]
Can confirm; the update fixed the issue. Thank you!
