### ISSUE TITLE
How to set `keepWindow` and `mayClose` of `removetab` to close a last window

### ISSUE THREAD

**Issue by chrisgrieser** [gdh1995/vimium-c#873]
**Describe the bug**
I am using `map w removetab keepWindow="mayClose"` so that when closing the last tab of a window, it also closes the window. This does work when there is more than one window, however, it does not seem to work in the last tab of the last window, it reopens my new-tab-page then. The behavior does not occur when using `cmd+w` to close the last tab of the last window.

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: Vivaldi
- Browser version: 5.7.2921.60 (Stable channel) (arm64) 
- Vimium C version: 1.99.96
- OS name and version: macOS 13.2 (M1)

**Comment by gdh1995** [comment]
Um you made some misunderstanding:
1. The comment of `keepWindow=""/always, mayClose` means `removeTab` support at least 2 parameters:
- 1. `keepWindow`: it can be `"always"`, or `""` by default
- 2. `mayClose`: it's a boolean and can be `true`, or `false` by default
2. if `mayClose` is true`, then `removeTab` won't keep any window existing, even if it's a last one
3. otherwise, when `mayClose` is not given or it's `false`:
- 1. if `keepWindow` is `"always"`, then Vimium C will try to keep all to-be-closed windows
- 2. otherwise, when `keepWindow` is `""` by default, Vimium C only keep a last normal window
  - 1. this means, if there has been a last normal window, and `removeTab` may close a 2nd normal window, then go ahead
  - 2. if a 2nd window is incognito, then still close it
  - 3. if there exists only 1 window, then prevent it from being closed

So in this case you may need `map w removeTab mayClose`.

**Comment by chrisgrieser** [comment]
Ah, I see! Thank you. I simply thought `""/` was result of an encoding error or something. I didn't figure out that that it meant empty string 🤦‍♂️ 

Thank you!

**Comment by yuan-ge** [comment]
I'm interested in the use of parameters too. But I can't find specific instruction of it. Hope the doc more specific.
