### ISSUE TITLE
[Feature Request] Implement Find(f) in Visaul Mode

### ISSUE THREAD

**Issue by Fuann-Kinoko** [gdh1995/vimium-c#875]
Would it be possible to **find** another character in visual mode, press semicolon to repeat last f/t jump, just like in vim?

**Comment by gdh1995** [comment]
`f` and `t` in VIM are too complicated to add in Vimium C, but you may enter FindMode from VisualMode by `/` and then use most existing shortcuts of Vimium C's FindMode:
1. press `/`
2. type a character or even a word to search
3. press `Ctrl+J` and `Ctrl+K` to find a next/previous match

**Comment by Fuann-Kinoko** [comment]
Agree, find mode is indeed sufficient. 

However, I'd prefer to:

1. Enter visual mode
2. Press `/`
3. Enter some words
4. The beginning of the selection area remains the same, and the end of the selection area jumps to the location of the matched word.
5. press `Ctrl+J` and `Ctrl+K` to find the next/previous match

Could this be implemented? 

Thanks for bringing such a great extension.

**Comment by gdh1995** [comment]
The idea sounds perfect! Thank you.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.99.99 has been published, and its VisualMode now supports `f` to show an embedded Find HUD and then extend selection to your query string.

**Comment by Fuann-Kinoko** [comment]
I guess there are some unintended behavior or perhaps a misunderstanding on my part regarding the usage of this feature?

E.g. in cursor mode, when I used the `/` search and press `n`, it entered visual mode and selected the matched word instead of jumping the cursor to it as intended.

Similarly, in cursor mode, I was unable to make a jump using the `f` command.

**Comment by gdh1995** [comment]
what did you mean by "cursor mode"?


when you are in FindMode, "n" key will be a plain letter added into the query word.&nbsp;


Do you want any shortcut to exit FindMode and enter VisualMode immediately?


What detailed actions do you expect when you press "f" in VisualMode, or your "cursor mode"?



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 26, 2023 00:24 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] [Feature Request] Implement Find(f) in VisaulMode (Issue #875)




 
I guess there are some unintended behavior or perhaps a misunderstanding on my part regarding the usage of this feature?
 
E.g. in cursor mode, when I used the / search and press n, it entered visual mode and selected the matched word instead of jumping the cursor to it as intended.
 
Similarly, in cursor mode, I was unable to make a jump using the f command.

**Comment by gdh1995** [comment]
This issue has been closed because it's inactive for a while. Feel free to reopen it or open a new one if only you like.
