### ISSUE TITLE
Search in PDF only scrolls on first hit

### ISSUE THREAD

**Issue by thisisrandy** [gdh1995/vimium-c#88]
Repro steps:

1. Open any pdf. I happened to be reading [this](https://arxiv.org/pdf/1904.09751.pdf) when I discovered the issue, so I'll use it as an example.
2. Search for any word which appears on multiple pages, e.g. "random."
3. Notice that if the word is out of view, the page will scroll to the first found occurrence as expected.
4. Press "n" any number of times.
5. Notice that the page does not scroll to the any subsequent occurrences, though it does highlight them as expected.

Hopefully that's clear. The expected behavior, if it isn't obvious, is for the page to scroll with the highlighted search term as it does in the non-PDF context.

**Comment by gdh1995** [comment]
What extension do you mean?

The default case is, a browser shows PDF in a priviledged "plugin" and only the inner search widget can work - then Vimium C's FindMode can not work at all.

If you're talking about the "PDF Viewer for Vimium C", then I'll test it in a few days.

**Comment by gdh1995** [comment]
When I scrolled down a little and made the first "Random" visible but the second not, `n` did fail to make a new search result visible. I'll test more to try to fix it.

PDF Viewer for Vimium C (and PDF Viewer) only render pages which are currently visible or "almost visible" (near to the current page), while text content of other pages are not put in DOM tree until they're scrolled into view. As a result, Vimium C can only search query text in 1~2 pages.

**Comment by thisisrandy** [comment]
Yes, I'm talking about the PDF viewer. Sorry, I assumed that would be clear, but I guess this repo covers multiple extensions.

**Comment by thisisrandy** [comment]
I think I understand what you're saying about pdf.js (that's what you use, right?) only rending nearby pages. It sounds like Vimium C relies on the DOM, whereas pdf.js is probably able to implement find correctly because it relies on some internal representation. Is that correct? I did notice when I was writing this up that Vimium C found fewer matches than Ctrl-F, but when I tried again, the numbers matched, so I thought I must have imagined the difference. I guess what was actually happening was that the whole document was in the DOM the second time since I had viewed each page.

In any event, it looks like you've already committed a fix for the scrolling part. Please let me know when you've published the fix so that I can test it out. Thanks!

**Comment by gdh1995** [comment]
About the original issue:
* it's because the underlying `window.find` usually scrolls found text into view, but in some situations it "fails"
  * this PDF and the word "random" is just an exact case, and normal web pages can only cause it

About releases:
* now that this issue does not break Vimium C, a new version will arrive in at least a week (aka, the next weekend)
  * I prefer to waiting a few weeks and releasing v1.79 directly.
* Here's a ZIP file to test the new commit: [vimium_c-1.78.6-chrome.zip](https://github.com/gdh1995/vimium-c/files/3837200/vimium_c-1.78.6-chrome.zip)


About my second paragraph
* The reason why I wrote it is, once I thought this issue is because of narrowed rendering
  * but a few hours ago I found the real reason, as mentioned above.
* Yes, Vimium C can only find words "in DOM", which is limited in pages using such a technology 
  * for example, PDF viewer, Docs and PPTs
  * this technology is developed to save memory and CPU - but with a side effect of make search harder
* even you "view each page one by one", only recent 2~3 pages will be in DOM, and those invisible ones will have been discarded.

**Comment by thisisrandy** [comment]
Confirmed working with 1.78.6.

Regarding what's kept in the DOM, it does seem that with a smallish PDF, the whole document is kept once it has been rendered, inasmuch as Vimium C is able to search the whole document, but I'm sure with a larger document the behavior would be to throw away far away pages as you describe.

Anyhow, thanks for the quick fix. I'll probably be using Ctrl-F in PDFs to make sure that I get full document coverage, but thanks for taking the time to explain why it isn't possible for you to do this directly in Vimium C.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.78.7 has been released.

In my plan, there won't be more v1.78.*, so if any new bug / regression found, it will be fixed in v1.79 in 20+ days.

**Comment by thisisrandy** [comment]
Confirmed working in 1.78.7. Thanks for your help!
