### ISSUE TITLE
yank bug in firefox

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#90]
hi
i have problem with yank in firefox(not other chromium based browser)
if you yank somethings in firefox, you can't access that with xclip
for example i use somethings like this 
```
url=$(xclip -o | dmenu -fn terminus-22:normal -p "URL " )
[[ -z $url ]] && exit
```
this command show clipboard content in dmenu.
if you yank somethings in firefox this command show you nothing , but everything work fine in chromium based browser like brave.
so i thinks somethings wrong in yank function for firefox

**Comment by gdh1995** [comment]
After you "yank", can you paste the string into Firefox address bar or a text box of web page?

**Comment by Monirzadeh** [comment]
yes i can use that in address bar or inside of web page

**Comment by gdh1995** [comment]
Then it's a problem about the concept of "Clipboard" and X11 (or Wayland if you're using it) - as far as I know, there're multiple clipboards in an X11 environment, so please consider using some other arguments of `xclip` (refer: https://unix.stackexchange.com/questions/22494/copy-file-to-xclip-and-paste-to-firefox)

**Comment by Monirzadeh** [comment]
> about the concept of "Clipboard" and X11 (or Wayland if you're using it) - as far as I know, there're multiple clipboards in an X11 environmen

why that work correct with brave?
if the problem is with xclip, it shouldn't work with brave?

**Comment by gdh1995** [comment]
What's your operating system with this issue?

**Comment by gdh1995** [comment]
Well, I think I've found the root cause:
1. In X11, the "primary" means what text is selected currently
  1. and only "clipboard" is the real "clipboard"
2. Vimium C uses different API to "copy" text into the clipboard
  1. on Chrome, it simulates selecting text and then copy
  2. on Firefox, it calls `navigator.clipboard.writeText` if only possible, which means no selecting actions occur.

I'll test more and try to work around this difference.

**Comment by Monirzadeh** [comment]
> What's your operating system with this issue?

Linux kubuntu

**Comment by gdh1995** [comment]
Well, after some tests I think, this issue is caused by Firefox's security policy about Vimium C's background process, and although there's indeed a solution for it, it will be too expensive - costs CPU and increases the code size of content scripts, while is not so reliable yet in some edge cases.

Therefore, I decide not to fix this case, and please use `-selection clipboard` instead.

If someone else is also interested in this, please put your opinions here and let me know.
