### ISSUE TITLE
Firefox: LinkHints.activateCopyLinkUrl doesn't copy to emacs clipboard

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [gdh1995/vimium-c#987]
**Describe the bug**

This is a niche bug related to Emacs and Firefox, where LinkHints.activateCopyLinkUrl doesn't copy to the emacs clipboard. The other Vimium-c related copy commands do work; it's just this one in particular that doesn't work. (I've experienced this problem with regular Vimium before).

**To Reproduce**

1. Visit any website with links on it
2. Use a keybinding that's bound to LinkHints.activateCopyLinkUrl
3. Paste into an emacs buffer. It will paste whatever was copied from before, and not the link from LinkHints.activateCopyLinkUrl

(Pasting works fine into any other desktop application)

**Browser, OS and Vimium C versions**

- Browser name: Firefox 
- Browser version: 115.0.2
- Vimium C version: 1.99.995
- OS name and version: Ubuntu (gnu/linux) 23.04

**Comment by gdh1995** [comment]
Why did you close this?


Is it because of your emacs configurations?



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 2, 2023 04:23 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Firefox: LinkHints.activateCopyLinkUrl doesn'tcopy to emacs clipboard (Issue #987)




 
Closed #987 as completed.

**Comment by tinglycraniumplacidly** [comment]
Yes, I just had to upgrade org-mode. In fact, when I copied into emacs directly, it worked properly. The problem was with the org-capture function in an older version of org-mode.
